// imates-react/src/components/display/MarkdownTitle.tsx
import React, { useMemo } from 'react'
import { useMessageRenderer } from '@/hooks/useMessageRenderer'
import '@/components/display/MarkdownTitle.css'

export interface MarkdownTitleProps {
  title?: string
}

export const MarkdownTitle: React.FC<MarkdownTitleProps> = ({
  title = '',
}) => {
  const { renderMessageContent } = useMessageRenderer()

  const truncateTitle = (text: string): string => {
    const maxLength = 20
    if (text.length <= maxLength) return text
    return text.substring(0, maxLength) + '...'
  }

  const renderedTitle = useMemo(() => {
    const content = title || '新会话'
    const truncated = truncateTitle(content)
    const rendered = renderMessageContent(truncated)
    return `<strong>${rendered}</strong>`
  }, [title, renderMessageContent])

  return (
    <div className="title-wrapper">
      <div 
        className="card-title markdown-title" 
        dangerouslySetInnerHTML={{ __html: renderedTitle }} 
      />
    </div>
  )
}

export default MarkdownTitle

// imates-web/src/components/display/MarkdownTitle.vue
<template>
  <div class="title-wrapper">
    <div class="card-title markdown-title" v-html="renderedTitle"></div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, nextTick } from 'vue'
import { useMessageRenderer } from '../../composables/useMessageRenderer'
import { MathJaxUtils } from '../../utils/math/mathjax'

const props = defineProps<{
  title: string
}>()

const { renderMessageContent } = useMessageRenderer()

// 截断 20 字符
const truncateTitle = (text: string): string => {
  const maxLength = 20
  if (text.length <= maxLength) return text
  return text.substring(0, maxLength) + '...'
}

const renderedTitle = computed(() => {
  // 直接使用原始标题，清洗逻辑已移除
  const content = props.title || '新会话'
  const truncated = truncateTitle(content)
  const rendered = renderMessageContent(truncated)
  return `<strong>${rendered}</strong>`
})

onMounted(async () => {
  await nextTick()
  // MathJax 渲染（如果需要）
})
</script>

<style scoped>
.title-wrapper {
  position: relative;
  flex: 1;
  min-width: 0;
  height: 24px;
}

.card-title {
  font-size: 14px;
  font-weight: 700;
  color: #1f2937;
  letter-spacing: -0.01em;
  white-space: nowrap;
  line-height: 24px;
  height: 24px;
  overflow: hidden;
}

:deep(.math) {
  display: inline-block;
  vertical-align: middle;
  font-size: 0.85em;
}
</style>
