// imates-app/src/components/StudentHandwritingOcrOverlay.tsx
import React, { useState, useEffect } from 'react';
import {
  StyleSheet,
  Text,
  View,
  Image,
  Pressable,
  LayoutChangeEvent,
} from 'react-native';

export interface StudentHandwritingOcrOverlayProps {
  questionData?: any[];
  scorePointList?: any[];
  focusedPointIndex?: number | null;
  activePointId?: string | null;
  onSelectPoint?: (payload: { point: any; index: number }) => void;
}

const getRegionBbox = (region: any) => {
  if (!Array.isArray(region?.bbox) || region.bbox.length < 4) return null;
  const [x1, y1, x2, y2] = region.bbox.slice(0, 4).map(Number);
  if ([x1, y1, x2, y2].some((v) => Number.isNaN(v))) return null;
  if (x2 <= x1 || y2 <= y1) return null;
  return { x1, y1, x2, y2 };
};

const isVirtualRegion = (region: any) => {
  const bbox = getRegionBbox(region);
  return bbox && bbox.x1 === 0 && bbox.y1 === 0 && bbox.x2 === 1 && bbox.y2 === 1;
};

const getOverlayPointRegions = (point: any) => {
  return Array.isArray(point?.matchedOcrRegions)
    ? point.matchedOcrRegions.filter(
        (region: any) => getRegionBbox(region) && !isVirtualRegion(region)
      )
    : [];
};

export function StudentHandwritingOcrOverlay({
  questionData = [],
  scorePointList = [],
  focusedPointIndex,
  activePointId,
  onSelectPoint,
}: StudentHandwritingOcrOverlayProps) {
  const [containerSize, setContainerSize] = useState<{ width: number; height: number }>({ width: 0, height: 0 });
  const [imageMeta, setImageMeta] = useState<{ width: number; height: number } | null>(null);

  const primaryItem = questionData && questionData.length > 0 ? questionData[0] : null;
  const imgUrl = primaryItem
    ? Array.isArray(primaryItem.answerData)
      ? primaryItem.answerData[0]
      : typeof primaryItem.answerData === 'string'
      ? primaryItem.answerData
      : primaryItem.studentAnswerImage || ''
    : '';

  useEffect(() => {
    if (imgUrl) {
      Image.getSize(
        imgUrl,
        (w, h) => {
          if (w > 0 && h > 0) {
            setImageMeta({ width: w, height: h });
          }
        },
        (err) => console.warn('[OcrOverlay] Image.getSize error:', err)
      );
    }
  }, [imgUrl]);

  const handleLayout = (e: LayoutChangeEvent) => {
    const layout = e?.nativeEvent?.layout;
    if (layout) {
      const { width, height } = layout;
      if (width > 0 && height > 0) {
        setContainerSize({ width, height });
      }
    }
  };

  const isPointActive = (point: any, index: number) => {
    if (activePointId && (point.id === activePointId || point.pointId === activePointId)) {
      return true;
    }
    if (focusedPointIndex !== null && focusedPointIndex !== undefined && focusedPointIndex === index) {
      return true;
    }
    return false;
  };

  const shouldShowPointRegions = (pointIndex: number) => {
    if (focusedPointIndex === null || focusedPointIndex === undefined) return true;
    return focusedPointIndex === pointIndex;
  };

  const getRegionStyle = (region: any) => {
    if (!imageMeta || !imageMeta.width || !imageMeta.height) {
      return { display: 'none' as const };
    }
    const bbox = getRegionBbox(region);
    if (!bbox) return { display: 'none' as const };

    const leftPct = (bbox.x1 / imageMeta.width) * 100;
    const topPct = (bbox.y1 / imageMeta.height) * 100;
    const widthPct = ((bbox.x2 - bbox.x1) / imageMeta.width) * 100;
    const heightPct = ((bbox.y2 - bbox.y1) / imageMeta.height) * 100;

    return {
      left: `${leftPct}%`,
      top: `${topPct}%`,
      width: `${Math.min(100, widthPct)}%`,
      height: `${Math.min(100, heightPct)}%`,
    } as any;
  };

  if (!imgUrl) return null;

  return (
    <View style={styles.answerImageCard}>
      <View style={styles.answerImageWrapper}>
        <View style={styles.studentImageContainer} onLayout={handleLayout}>
          <Image
            source={{ uri: imgUrl }}
            style={styles.studentImage}
            resizeMode="contain"
            onError={() => {
              console.warn('[OcrOverlay] 手写图片资源不可访问或失效:', imgUrl);
              setImageMeta(null);
            }}
          />

          {/* OCR 划线覆盖区域 */}
          {scorePointList.map((point, pointIndex) => {
            if (!shouldShowPointRegions(pointIndex)) return null;
            const regions = getOverlayPointRegions(point);
            const active = isPointActive(point, pointIndex);
            const isHit = !!point.hit;

            return regions.map((region: any, regionIndex: number) => {
              const rStyle = getRegionStyle(region);
              return (
                <Pressable
                  key={`${point.id || point.pointId || pointIndex}-${regionIndex}`}
                  style={[
                    styles.ocrRegion,
                    isHit ? styles.hitRegion : styles.nohitRegion,
                    active && styles.activeRegion,
                    rStyle,
                  ]}
                  onPress={() => onSelectPoint && onSelectPoint({ point, index: pointIndex })}
                >
                  {!region.suppressMarker && (
                    <View style={styles.regionMarker}>
                      <View style={[styles.statusIconCircle, isHit ? styles.hitIconCircle : styles.nohitIconCircle]}>
                        <Text style={styles.statusIconText}>{isHit ? '✓' : '✕'}</Text>
                      </View>
                      <View style={[styles.indexBadge, isHit ? styles.hitBadge : styles.nohitBadge]}>
                        <Text style={styles.indexBadgeText}>
                          {point.displayIndex || pointIndex + 1}
                        </Text>
                      </View>
                    </View>
                  )}
                </Pressable>
              );
            });
          })}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  answerImageCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    overflow: 'hidden',
    boxSizing: 'border-box' as any,
  },
  answerImageWrapper: {
    position: 'relative',
    width: '100%',
    minHeight: 180,
    maxHeight: 520,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    overflow: 'hidden',
    padding: 8,
  },
  studentImageContainer: {
    position: 'relative',
    maxWidth: '100%',
    maxHeight: 504,
    alignItems: 'center',
    justifyContent: 'center',
  },
  studentImage: {
    width: 320,
    height: 380,
    maxWidth: '100%',
    maxHeight: 504,
    borderRadius: 4,
  },
  ocrRegion: {
    position: 'absolute',
    borderRadius: 4,
    zIndex: 10,
  },
  hitRegion: {
    backgroundColor: 'rgba(110, 85, 255, 0.22)',
  },
  nohitRegion: {
    backgroundColor: 'rgba(220, 100, 100, 0.25)',
  },
  activeRegion: {
    borderWidth: 2,
    borderColor: '#6E55FF',
    zIndex: 30,
  },
  regionMarker: {
    position: 'absolute',
    top: '50%',
    right: -48,
    transform: [{ translateY: -12 }],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    zIndex: 40,
  },
  statusIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hitIconCircle: {
    backgroundColor: '#6E55FF',
  },
  nohitIconCircle: {
    backgroundColor: '#FF3B30',
  },
  statusIconText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  indexBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hitBadge: {
    backgroundColor: '#6E55FF',
  },
  nohitBadge: {
    backgroundColor: '#FF3B30',
  },
  indexBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
});

// imates-web/src/components/display/StudentHandwritingOcrOverlay.vue
<script setup>
import { ref } from 'vue'
import correctIcon from '/icons/correct.svg'
import operationErrorIcon from '/icons/operation_error.svg'
import topicReviewErrorIcon from '/icons/topic_review_error.svg'
import thoughtErrorIcon from '/icons/thought_error.svg'

const props = defineProps({
  questionData: {
    type: Array,
    default: () => [],
  },
  scorePointList: {
    type: Array,
    default: () => [],
  },
  focusedPointIndex: {
    type: Number,
    default: null,
  },
  activePointId: {
    type: String,
    default: '',
  },
})

const isPointActive = (point, pointIndex) => {
  const pId = String(point?.pointId || point?.id || '')
  if (props.activePointId && pId === String(props.activePointId)) {
    return true
  }
  if (props.focusedPointIndex !== null && props.focusedPointIndex === pointIndex) {
    return true
  }
  return false
}

const emit = defineEmits(['select-point', 'select-region'])

const handleRegionClick = (point, pointIndex, region) => {
  console.log('[StudentHandwritingOcrOverlay] 🎯 OCR 划线区域被点击:', { pointIndex, point, region })
  emit('select-point', { point, index: pointIndex, region })
  emit('select-region', { point, pointIndex, region })
}

const imageMetaMap = ref({})

const handleImageLoad = (index, event) => {
  const img = event.target
  imageMetaMap.value[index] = {
    width: img.naturalWidth || img.width,
    height: img.naturalHeight || img.height,
  }
}

const getRegionBbox = (region) => {
  if (!Array.isArray(region?.bbox) || region.bbox.length < 4) return null
  const [x1, y1, x2, y2] = region.bbox.slice(0, 4).map(Number)
  if ([x1, y1, x2, y2].some((value) => Number.isNaN(value))) return null
  if (x2 <= x1 || y2 <= y1) return null
  return { x1, y1, x2, y2 }
}

const isVirtualRegion = (region) => {
  const bbox = getRegionBbox(region)
  return bbox && bbox.x1 === 0 && bbox.y1 === 0 && bbox.x2 === 1 && bbox.y2 === 1
}

const getPointRegions = (item) => {
  return Array.isArray(item?.matchedOcrRegions)
    ? item.matchedOcrRegions.filter(
        (region) => getRegionBbox(region) && !isVirtualRegion(region),
      )
    : []
}

const getRegionSourceIndex = (region) => region?.source_index ?? region?.sourceIndex ?? ''

const getRegionIdentity = (region) => {
  const bbox = getRegionBbox(region)
  if (!bbox) return ''
  return [getRegionSourceIndex(region), bbox.x1, bbox.y1, bbox.x2, bbox.y2].join('-')
}

const getNoHitRegionIdentitySet = () => {
  return new Set(
    (props.scorePointList || [])
      .filter((point) => !point?.hit)
      .flatMap((point) => getPointRegions(point).map(getRegionIdentity))
      .filter(Boolean),
  )
}

const getOverlayPointRegions = (point) => {
  const noHitRegionSet = getNoHitRegionIdentitySet()
  return getPointRegions(point).map((region) => ({
    ...region,
    suppressMarker: !!point?.hit && noHitRegionSet.has(getRegionIdentity(region)),
  }))
}

const shouldShowPointRegions = (pointIndex) =>
  props.focusedPointIndex === null || props.focusedPointIndex === pointIndex

const getRegionStyle = (region, imageIndex) => {
  const meta = imageMetaMap.value[imageIndex]
  if (!meta?.width || !meta?.height || !Array.isArray(region?.bbox)) {
    return { display: 'none' }
  }

  const bbox = getRegionBbox(region)
  if (!bbox || isVirtualRegion(region)) {
    return { display: 'none' }
  }

  const x1 = Math.max(0, Math.min(bbox.x1, meta.width))
  const y1 = Math.max(0, Math.min(bbox.y1, meta.height))
  const x2 = Math.max(0, Math.min(bbox.x2, meta.width))
  const y2 = Math.max(0, Math.min(bbox.y2, meta.height))
  const width = Math.max(0, x2 - x1)
  const height = Math.max(0, y2 - y1)

  return {
    left: `${(x1 / meta.width) * 100}%`,
    top: `${(y1 / meta.height) * 100}%`,
    width: `${Math.min(100, (width / meta.width) * 100)}%`,
    height: `${Math.min(100, (height / meta.height) * 100)}%`,
  }
}

const getIconForPoint = (point) => {
  if (point?.hit) {
    return correctIcon
  }
  const errType = String(point?.potentialErrorType || '')
  if (errType.includes('操作')) {
    return operationErrorIcon
  }
  if (errType.includes('审题')) {
    return topicReviewErrorIcon
  }
  return thoughtErrorIcon
}
</script>

<template>
  <div v-if="questionData && questionData.length > 0" class="images-list">
    <div
      v-for="(item, index) in questionData"
      :key="item.questionId || index"
      class="answer-image-card"
    >
      <div class="answer-image-wrapper">
        <div class="student-image-container" :data-image-index="index">
          <template v-if="Array.isArray(item.answerData)">
            <img
              v-for="(imgUrl, imgIdx) in item.answerData"
              :key="imgIdx"
              class="student-image"
              :src="imgUrl"
              alt="学生作答图片"
              @load="handleImageLoad(index, $event)"
            />
          </template>
          <img
            v-else-if="typeof item.answerData === 'string'"
            class="student-image"
            :src="item.answerData"
            alt="学生作答图片"
            @load="handleImageLoad(index, $event)"
          />

          <!-- OCR 划线覆盖图层 -->
          <template v-if="index === 0">
            <template
              v-for="(point, pointIndex) in scorePointList || []"
              :key="point.pointId || point.id || pointIndex"
            >
              <template v-if="shouldShowPointRegions(pointIndex)">
                <div
                  v-for="(region, regionIndex) in getOverlayPointRegions(point)"
                  :key="`${point.pointId || point.id || pointIndex}-${regionIndex}`"
                  :data-region-key="`${pointIndex}-${index}-${regionIndex}`"
                  :class="[
                    'ocr-region',
                    point.hit ? 'is-hit' : 'is-nohit',
                    region.suppressMarker ? 'is-suppressed' : '',
                    isPointActive(point, pointIndex) ? 'is-active-point' : '',
                  ]"
                  :style="getRegionStyle(region, index)"
                  @click.stop="handleRegionClick(point, pointIndex, region)"
                >
                  <span v-if="!region.suppressMarker" class="region-marker">
                    <span class="region-status-icon">
                      <img
                        :src="getIconForPoint(point)"
                        :alt="point.hit ? '命中' : '未命中'"
                        class="marker-svg-icon"
                      />
                    </span>
                    <span
                      class="region-index"
                      :class="point.hit ? 'is-hit-badge' : 'is-nohit-badge'"
                    >
                      {{ point.displayIndex || pointIndex + 1 }}
                    </span>
                  </span>
                </div>
              </template>
            </template>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
.images-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;

  .answer-image-card {
    width: 100%;
    background: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.05);
    overflow: hidden;
    box-sizing: border-box;

    .answer-image-wrapper {
      position: relative;
      width: 100%;
      min-height: 180px;
      max-height: 520px;
      display: flex;
      justify-content: center;
      align-items: center;
      background: #f8fafc;
      overflow: hidden;
      padding: 8px;
      box-sizing: border-box;

      .student-image-container {
        position: relative;
        display: inline-block;
        max-width: 100%;
        max-height: 504px;

        .student-image {
          max-width: 100%;
          max-height: 504px;
          width: auto;
          height: auto;
          display: block;
          object-fit: contain;
          border-radius: 4px;
        }

        .ocr-region {
          position: absolute;
          border: none;
          pointer-events: auto;
          cursor: pointer;
          user-select: none;
          -webkit-tap-highlight-color: transparent;
          outline: none;

          &:hover,
          &:active,
          &:focus {
            outline: none;
            box-shadow: none;
          }

          /* 激活/选中的采分点：增加 2px 边框 */
          &.is-active-point {
            border: 2px solid #6e55ff !important;
            box-shadow: none !important;
            border-radius: 4px;
            z-index: 20;
          }

          /* 命中遮罩（柔和紫色半透明） */
          &.is-hit {
            background: rgba(110, 85, 255, 0.22);
          }

          /* 未命中遮罩（柔和粉红半透明） */
          &.is-nohit {
            background: rgba(220, 100, 100, 0.25);
          }

          &.is-suppressed {
            opacity: 0.5;
          }

          /* 右侧标志容器 (SVG 图标 + 圆形序号) */
          .region-marker {
            position: absolute;
            top: 50%;
            right: -56px;
            transform: translateY(-50%);
            display: flex;
            align-items: center;
            gap: 4px;
            background: transparent !important;
            border: none !important;
            box-shadow: none !important;
            padding: 0;
            z-index: 10;

            .region-status-icon {
              display: flex;
              align-items: center;
              justify-content: center;

              .marker-svg-icon {
                width: 30px;
                height: 30px;
                display: block;
                object-fit: contain;
              }
            }

            .region-index {
              width: 18px;
              height: 18px;
              border-radius: 50%;
              display: flex;
              align-items: center;
              justify-content: center;
              font-size: 11px;
              font-weight: 700;
              color: #ffffff;
              flex-shrink: 0;

              &.is-hit-badge {
                background: #6e55ff;
              }

              &.is-nohit-badge {
                background: #ff3b30;
              }
            }
          }
        }
      }
    }
  }
}
</style>
