// imates-web/src/components/base/Textarea.vue
<template>
  <div class="auto-height-textarea-container">
    <textarea
      ref="textareaRef"
      :value="modelValue"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      :maxlength="maxlength"
      class="auto-height-textarea"
      @input="handleInput"
      @keydown="handleKeydown"
      @focus="$emit('focus', $event)"
      @blur="$emit('blur', $event)"
    />

    <q-btn
      v-if="showActionButton"
      :class="actionButtonClass"
      :color="actionButtonColor"
      :icon="actionButtonIcon"
      :loading="actionButtonLoading"
      :disable="actionButtonDisabled"
      :round="actionButtonRound"
      :size="actionButtonSize"
      @click="$emit('action-click', $event)"
    >
      <slot name="action-button"></slot>
    </q-btn>
  </div>
</template>

<script setup lang="ts">
import { ref, nextTick, watch, onMounted } from 'vue'

interface Props {
  modelValue: string
  placeholder?: string
  disabled?: boolean
  readonly?: boolean
  maxlength?: number
  minHeight?: number
  maxHeight?: number
  showActionButton?: boolean
  actionButtonClass?: string
  actionButtonColor?: string
  actionButtonIcon?: string
  actionButtonLoading?: boolean
  actionButtonDisabled?: boolean
  actionButtonRound?: boolean
  actionButtonSize?: string
}

interface Emits {
  (e: 'update:modelValue', value: string): void
  (e: 'input', event: Event): void
  (e: 'keydown', event: KeyboardEvent): void
  (e: 'focus', event: FocusEvent): void
  (e: 'blur', event: FocusEvent): void
  (e: 'action-click', event: Event): void
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: '',
  disabled: false,
  readonly: false,
  minHeight: 44,
  maxHeight: 120,
  showActionButton: false,
  actionButtonClass: '',
  actionButtonColor: 'primary',
  actionButtonIcon: '',
  actionButtonLoading: false,
  actionButtonDisabled: false,
  actionButtonRound: true,
  actionButtonSize: ''
})

const emit = defineEmits<Emits>()

const textareaRef = ref<HTMLTextAreaElement | null>(null)

const handleInput = (event: Event) => {
  const target = event.target as HTMLTextAreaElement
  const value = target.value

  emit('update:modelValue', value)
  emit('input', event)

  // 自动调整高度
  adjustHeight()
}

const handleKeydown = (event: KeyboardEvent) => {
  emit('keydown', event)
}

const adjustHeight = () => {
  if (!textareaRef.value) return

  const textarea = textareaRef.value

  // 重置高度以获取正确的 scrollHeight
  textarea.style.height = 'auto'

  // 计算新的高度
  const scrollHeight = textarea.scrollHeight
  const newHeight = Math.min(Math.max(scrollHeight, props.minHeight), props.maxHeight)

  textarea.style.height = `${newHeight}px`
}

// 监听 modelValue 变化，调整高度
watch(() => props.modelValue, () => {
  nextTick(() => {
    adjustHeight()
  })
}, { immediate: true })

onMounted(() => {
  adjustHeight()
})
</script>

<style scoped>
.auto-height-textarea-container {
  position: relative;
  width: 100%;
}

.auto-height-textarea {
  width: 100%;
  min-height: v-bind('props.minHeight + "px"');
  max-height: v-bind('props.maxHeight + "px"');
  padding: 12px 60px 12px 12px;
  border: 1px solid #7a7cff;
  border-radius: 16px;
  background: white;
  font-size: 14px;
  line-height: 1.6;
  color: #333;
  resize: none;
  overflow-y: auto;
  transition: all 0.2s ease;
  box-sizing: border-box;
  outline: none;
}

.auto-height-textarea:focus {
  border-color: #5a5cd8;
  box-shadow: 0 4px 16px rgba(122, 124, 255, 0.25), 0 2px 4px rgba(122, 124, 255, 0.15);
}

.auto-height-textarea::placeholder {
  color: #999;
  font-size: 14px;
}

.auto-height-textarea:disabled {
  background: #f5f5f5;
  color: #999;
  cursor: not-allowed;
}

/* Action button styles */
.auto-height-textarea-container :deep(.q-btn) {
  position: absolute;
  top: 12px;
  right: 12px;
  width: 40px;
  height: 40px;
  z-index: 10;
}
</style>

// imates-react/src/components/base/Textarea.tsx
import React, { useRef, useEffect, useCallback } from 'react'
import './Textarea.css'

export interface TextareaProps {
  value: string
  placeholder?: string
  disabled?: boolean
  readonly?: boolean
  maxlength?: number
  minHeight?: number
  maxHeight?: number
  showActionButton?: boolean
  actionButtonClass?: string
  actionButtonIcon?: string // 增加此属性
  actionButtonDisabled?: boolean
  actionButtonLoading?: boolean
  onChange?: (value: string) => void
  onFocus?: (e: React.FocusEvent) => void
  onBlur?: (e: React.FocusEvent) => void
  onKeyDown?: (e: React.KeyboardEvent) => void
  onActionClick?: (e: React.MouseEvent) => void
  isLoading?: boolean // 增加此属性
}

export const Textarea: React.FC<TextareaProps> = ({
  value,
  placeholder = '',
  disabled = false,
  readonly = false,
  maxlength,
  minHeight = 44,
  maxHeight = 120,
  showActionButton = false,
  actionButtonClass = '',
  actionButtonIcon = 'search',
  actionButtonDisabled = false,
  actionButtonLoading = false,
  onChange,
  onFocus,
  onBlur,
  onKeyDown,
  onActionClick,
  isLoading = false,
}) => {
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  const adjustHeight = useCallback(() => {
    const textarea = textareaRef.current
    if (!textarea) return

    textarea.style.height = 'auto'
    const scrollHeight = textarea.scrollHeight
    const newHeight = Math.min(Math.max(scrollHeight, minHeight), maxHeight)
    textarea.style.height = `${newHeight}px`
  }, [minHeight, maxHeight])

  useEffect(() => {
    adjustHeight()
  }, [value, adjustHeight])

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onChange?.(e.target.value)
    adjustHeight()
  }

  return (
    <div className="auto-height-textarea-container">
      <textarea
        ref={textareaRef}
        className="auto-height-textarea"
        value={value}
        placeholder={placeholder}
        disabled={disabled}
        readOnly={readonly}
        maxLength={maxlength}
        onChange={handleInput}
        onFocus={onFocus}
        onBlur={onBlur}
        onKeyDown={onKeyDown}
      />

      {showActionButton && (
        <button
          type="button"
          className={`auto-height-action-btn ${actionButtonClass} ${actionButtonLoading || isLoading ? 'is-loading' : ''}`}
          disabled={actionButtonDisabled || actionButtonLoading || isLoading}
          onClick={onActionClick}
        >
          {actionButtonLoading || isLoading ? (
            <div className="loading-spinner small"></div>
          ) : actionButtonIcon === 'search' ? (
            <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
              <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/>
            </svg>
          ) : (
            <i className="material-icons">{actionButtonIcon}</i>
          )}
        </button>
      )}
    </div>
  )
}

export default Textarea
