// imates-MiniApp/src/views/MyProfileView.vue
<template>
  <view class="profile-container">
    <!-- 功能卡片区域 -->
    <RubberBandList>
      <view class="features-section">
        <view class="content-wrapper">
          <!-- 加入课堂卡片 -->
          <view
            class="feature-card"
            :class="{ 'in-class': isInClass }"
            @click="toggleJoinClass"
          >
            <image :src="joinClassIcon" mode="aspectFit" class="card-icon" />
          </view>
          <!-- 老师答疑卡片 -->
          <view class="feature-card" @click="openTeacherQA">
            <image :src="teacherQAIcon" mode="aspectFit" class="card-icon" />
          </view>
          <!-- 我的收藏卡片 -->
          <view class="feature-card" @click="showFavorites">
            <image :src="myFavoritesIcon" mode="aspectFit" class="card-icon" />
          </view>
          <!-- 草稿本卡片 -->
          <view class="feature-card" @click="openDraftNotebook">
            <image :src="drawIcon" mode="aspectFit" class="card-icon" />
          </view>
          <!-- 意见反馈卡片 -->
          <view class="feature-card" @click="showFeedback">
            <image :src="feedbackIcon" mode="aspectFit" class="card-icon" />
            <view class="notification-badge" v-if="userClientUnreadCount > 0">
              <text>{{ userClientUnreadCount }}</text>
            </view>
          </view>
        </view>
      </view>
    </RubberBandList>

    <!-- 加入课堂确认对话框 -->
    <Dialog
      ref="joinClassDialogRef"
      :title="isInClass ? '确认退出课堂' : '课堂提示'"
      :confirmButtonText="isInClass ? '确认退出' : '确认加入'"
      cancelButtonText="取消"
      @confirm="confirmJoinClass"
      @cancel="handleJoinClassDialogCancel"
    >
      <view class="exit-classroom" v-if="isInClass">
        <view class="exit-icon">!</view>
        <view class="exit-text">
          <view class="primary">确认退出课堂？</view>
          <view class="secondary">退出后将不能和老师互动，且投屏会结束。</view>
        </view>
      </view>

      <view class="join-classroom-content" v-else>
        <view class="join-classroom-body">
          <view class="status-text">确认加入课堂？</view>
        </view>
      </view>
    </Dialog>

    <!-- 退出登录确认对话框 -->
    <Dialog
      ref="logoutDialogRef"
      title="退出确认"
      confirmButtonText="退出"
      cancelButtonText="取消"
      @confirm="confirmLogout"
      @cancel="cancelLogout"
    >
      <view class="logout-dialog-content">确定要退出登录吗？</view>
    </Dialog>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useUserClientStore } from '../stores/userClientStore'
import { androidBridge } from '../services/business/android-bridge'
import { showMessage } from '../utils'
import {
  authService,
  getUserInfo,
  getXuebanToken,
  setUserInfo,
} from '../services'
import RubberBandList from '../components/base/VirtualScroll.vue'
import Dialog from '../components/base/Dialog.vue'

// 资源路径适配
const drawIcon = '/static/icons/draw.svg'
const joinClassIcon = '/static/icons/join_class.svg'
const myFavoritesIcon = '/static/icons/my_favorites.svg'
const feedbackIcon = '/static/icons/feedback.svg'
const teacherQAIcon = '/static/icons/teacher_qa.svg'

const userClientStore = useUserClientStore()

// 状态
const isInClass = ref(false)
const isProjecting = ref(false)
const logoutDialogRef = ref<InstanceType<typeof Dialog> | null>(null)
const joinClassDialogRef = ref<InstanceType<typeof Dialog> | null>(null)

// 未读消息
const userClientUnreadCount = computed(() => userClientStore.unreadCount)

const userInfo = computed(() => {
  return (
    getUserInfo() || {
      id: '',
      name: '',
      avatar: '',
      roles: [] as string[],
    }
  )
})

const checkClassroomStatus = () => {
  const status = androidBridge.getClassroomStatus()
  if (status && status.isInClass === true) {
    isInClass.value = true
    isProjecting.value = status.status === 'streaming'
  } else {
    isInClass.value = false
    isProjecting.value = false
  }
}

onMounted(() => {
  loadUserInfo()
  checkClassroomStatus()

  androidBridge.onClassroomJoined(() => {
    isInClass.value = true
    showMessage('已加入课堂', 'success')
  })
  androidBridge.onClassroomExited(() => {
    isInClass.value = false
    showMessage('已退出课堂', 'info')
  })
})

const loadUserInfo = async () => {
  try {
    const cached = getUserInfo()
    if (cached) return

    const token = getXuebanToken()
    if (!token) return

    const userData = await authService.getUserInfo(token)
    if (userData) {
      setUserInfo(userData)
    }
  } catch (error) {
    console.error('加载用户信息失败:', error)
  }
}

const toggleJoinClass = () => {
  joinClassDialogRef.value?.openDialog()
}

const handleJoinClassDialogCancel = () => {
  joinClassDialogRef.value?.closeDialog()
}

const confirmJoinClass = () => {
  joinClassDialogRef.value?.closeDialog()

  if (isInClass.value) {
    const ok = androidBridge.exitClassroom()
    if (ok) {
      isInClass.value = false
      isProjecting.value = false
      showMessage('已退出课堂', 'success')
    } else {
      showMessage('退出课堂失败', 'error')
    }
    return
  }

  const studentId = userInfo.value.id || ''
  const studentName = userInfo.value.name || '用户'
  const isGuest = !studentId

  const ok = androidBridge.joinClassroom(studentId, studentName, isGuest)
  if (ok) {
    isInClass.value = true
    showMessage('已加入课堂', 'success')
  } else {
    showMessage('加入课堂失败', 'error')
  }
}

const showFeedback = () => {
  // 小程序端反馈通常跳转到专门的反馈页面或使用客服功能
  ;(uni as any).navigateTo({ url: '/pages/feedback/index' })
}

const showFavorites = () => {
  ;(uni as any).navigateTo({ url: '/pages/favorites/list' })
}

const openDraftNotebook = () => {
  ;(uni as any).navigateTo({ url: '/pages/canvas/canvas' })
}

const openTeacherQA = () => {
  ;(uni as any).navigateTo({ url: '/pages/chat/chat?type=teacher' })
}

const handleLogout = () => {
  logoutDialogRef.value?.openDialog()
}

const cancelLogout = () => {
  logoutDialogRef.value?.closeDialog()
}

const confirmLogout = async () => {
  try {
    logoutDialogRef.value?.closeDialog()

    if (androidBridge.isAndroidBridgeAvailable()) {
      try { androidBridge.stopScreenProjection() } catch {}
      try { androidBridge.exitClassroom() } catch {}
    }

    // 清理存储并重定向
    ;(uni as any).reLaunch({ url: '/pages/login/login' })
    showMessage('已退出登录', 'success')
  } catch (error) {
    console.error('退出登录失败:', error)
    showMessage('退出登录失败，请重试', 'error')
  }
}
</script>

<style scoped>
.profile-container {
  padding: 40rpx 32rpx;
  height: 100%;
  box-sizing: border-box;
}

.features-section {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  margin-bottom: 48rpx;
  max-width: 1200rpx;
  margin-left: auto;
  margin-right: auto;
}

.content-wrapper {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 80rpx;
  padding-top: 40rpx;
}

.feature-card {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 112rpx;
  height: 112rpx;
  flex-shrink: 0;
}

.card-icon {
  width: 168rpx;
  height: 168rpx;
  z-index: 1;
}

.notification-badge {
  position: absolute;
  top: -12rpx;
  right: -12rpx;
  min-width: 36rpx;
  height: 36rpx;
  background: #ef4444;
  color: white;
  border-radius: 18rpx;
  border: 4rpx solid #ffffff;
  font-size: 22rpx;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0 8rpx;
  box-sizing: border-box;
  z-index: 2;
}

.in-class::before {
  content: '';
  position: absolute;
  top: -46rpx;
  left: -46rpx;
  right: -46rpx;
  bottom: -46rpx;
  background: radial-gradient(circle, rgba(147, 51, 234, 1.2) 0%, rgba(147, 51, 234, 0.9) 20%, rgba(147, 51, 234, 0.6) 40%, rgba(147, 51, 234, 0.3) 60%, rgba(147, 51, 234, 0.1) 80%, rgba(147, 51, 234, 0.02) 100%);
  border-radius: 50%;
  z-index: 0;
  animation: breathe 2s ease-in-out infinite;
}

@keyframes breathe {
  0% { opacity: 1; }
  50% { opacity: 0.3; }
  100% { opacity: 1; }
}

.exit-classroom {
  display: flex;
  gap: 24rpx;
  align-items: center;
}

.exit-icon {
  width: 68rpx;
  height: 68rpx;
  border-radius: 20rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(239, 68, 68, 0.12);
  color: #ef4444;
  font-weight: 800;
  flex-shrink: 0;
}

.exit-text {
  display: flex;
  flex-direction: column;
  gap: 12rpx;
}

.exit-text .primary {
  font-size: 30rpx;
  font-weight: 600;
  color: #111827;
}

.exit-text .secondary {
  font-size: 26rpx;
  color: #6b7280;
}

.join-classroom-content {
  padding: 28rpx 32rpx;
}

.status-text {
  font-size: 26rpx;
  color: #6b7280;
}

.logout-dialog-content {
  font-size: 30rpx;
  color: #4b5563;
}

@media (max-width: 480px) {
  .content-wrapper {
    grid-template-columns: repeat(2, 1fr);
  }
}
</style>

// imates-react/src/views/MyProfileView.tsx
import React, { useState, useEffect, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { androidBridge } from '@/services/business/android-bridge'
import { authService, getUserInfo, getXuebanToken, setUserInfo } from '../services'
import { showMessage } from '@/utils'
import { Dialog } from '../components/base/Dialog'
import './MyProfileView.css'

// 导入图标
import drawIcon from '/icons/draw.svg'
import joinClassIcon from '/icons/join_class.svg'
import myFavoritesIcon from '/icons/my_favorites.svg'
import feedbackIcon from '/icons/feedback.svg'
import teacherQAIcon from '/icons/teacher_qa.svg'

export const MyProfileView: React.FC = () => {
  const navigate = useNavigate()
  
  // 状态数据
  const [isInClass, setIsInClass] = useState(false)
  const [isProjecting, setIsProjecting] = useState(false)
  const [userClientUnreadCount] = useState(0)
  const [showJoinClassDialog, setShowJoinClassDialog] = useState(false)

  // 获取用户信息
  const userInfo = useMemo(() => {
    return getUserInfo() || { id: '', name: '', avatar: '', roles: [] }
  }, [])

  // 检查课堂状态
  const checkClassroomStatus = () => {
    const status = androidBridge.getClassroomStatus()
    if (status && status.isInClass === true) {
      setIsInClass(true)
      setIsProjecting(status.status === 'streaming')
    } else {
      setIsInClass(false)
      setIsProjecting(false)
    }
  }

  useEffect(() => {
    checkClassroomStatus()

    // 绑定原生事件
    androidBridge.onClassroomJoined(() => {
      setIsInClass(true)
      showMessage('已加入课堂', 'success')
    })
    androidBridge.onClassroomExited(() => {
      setIsInClass(false)
      showMessage('已退出课堂', 'info')
    })
    androidBridge.onClassroomStatusChanged((newStatus: any) => {
      const inClass = !!newStatus?.isInClass
      setIsInClass(inClass)
      setIsProjecting(newStatus?.status === 'streaming')
    })
    androidBridge.onScreenProjectionStarted(() => setIsProjecting(true))
    androidBridge.onScreenProjectionStopped(() => setIsProjecting(false))
  }, [])

  const toggleJoinClass = () => {
    setShowJoinClassDialog(true)
  }

  const confirmJoinClass = () => {
    setShowJoinClassDialog(false)

    if (!androidBridge.isAndroidBridgeAvailable()) {
      showMessage('Web 演示模式：已完成教室选择，但当前环境不支持真实加入课堂', 'info')
      return
    }

    if (isInClass) {
      const ok = androidBridge.exitClassroom()
      if (ok) {
        setIsInClass(false)
        setIsProjecting(false)
        showMessage('已退出课堂', 'success')
      } else {
        showMessage('退出课堂失败', 'error')
      }
      return
    }

    const studentId = userInfo.id || ''
    const studentName = userInfo.name || '用户'
    const isGuest = !studentId

    const ok = androidBridge.joinClassroom(studentId, studentName, isGuest)
    if (ok) {
      setIsInClass(true)
      showMessage('已加入课堂', 'success')
    } else {
      showMessage('加入课堂失败', 'error')
    }
  }

  const openTeacherQADialog = () => {
    console.log('[MyProfileView] 打开老师答疑')
  }

  const showFavorites = () => {
    navigate('/app/my-favorites')
  }

  const openDraftNotebook = () => {
    navigate('/app/draft-notebook')
  }

  const showFeedback = () => {
    console.log('[MyProfileView] 打开反馈')
  }

  return (
    <div className="profile-container">
      <div className="features-section">
        <div className="content-wrapper">
          {/* 加入课堂卡片 */}
          <div
            className={`feature-card ${isInClass ? 'in-class' : ''}`}
            onClick={toggleJoinClass}
          >
            <img src={joinClassIcon} alt="加入课堂" className="card-icon" />
          </div>

          {/* 老师答疑卡片 */}
          <div className="feature-card" onClick={openTeacherQADialog}>
            <img src={teacherQAIcon} alt="老师答疑" className="card-icon" />
          </div>

          {/* 我的收藏卡片 */}
          <div className="feature-card" onClick={showFavorites}>
            <img src={myFavoritesIcon} alt="我的收藏" className="card-icon" />
          </div>

          {/* 草稿本卡片 */}
          <div className="feature-card" onClick={openDraftNotebook}>
            <img src={drawIcon} alt="草稿本" className="card-icon" />
          </div>

          {/* 意见反馈卡片 */}
          <div className="feature-card" onClick={showFeedback}>
            <img src={feedbackIcon} alt="在线客服" className="card-icon" />
            {userClientUnreadCount > 0 && (
              <span className="notification-badge">{userClientUnreadCount}</span>
            )}
          </div>
        </div>
      </div>

      {/* 对话框 */}
      <Dialog
        open={showJoinClassDialog}
        title={isInClass ? '确认退出课堂' : '课堂提示'}
        onClose={() => setShowJoinClassDialog(false)}
        onConfirm={confirmJoinClass}
        confirmButtonText={isInClass ? '确认退出' : '确认加入'}
      >
        {isInClass ? (
          <div className="exit-classroom">
            <div className="exit-icon">!</div>
            <div className="exit-text">
              <div className="primary">确认退出课堂？</div>
              <div className="secondary">退出后将不能和老师互动，且投屏会结束。</div>
            </div>
          </div>
        ) : (
          <div className="join-classroom-content">
            <div className="status-text">确认加入课堂？</div>
          </div>
        )}
      </Dialog>
    </div>
  )
}

export default MyProfileView
