// imates-web/src/components/exercise/ChoiceQuestion.vue
<template>
  <BaseQuestion :question="question" :show-title="showTitle" :show-analysis="showAnalysis">
    <div class="choice-options">
      <div 
        v-for="opt in options" 
        :key="opt.label"
        class="option-item"
        :class="{ 
          selected: isSelected(opt.label),
          correct: isSelected(opt.label) && isCorrect(opt.label) && disabled,
          wrong: isSelected(opt.label) && !isCorrect(opt.label) && disabled
        }"
        @click="handleSelect(opt.label)"
      >
        <div class="option-label">{{ opt.label }}</div>
        <div class="option-text" v-html="renderMessageContent(opt.text)"></div>
        <div class="option-status-icon" v-if="disabled && isSelected(opt.label)">
          <q-icon v-if="isCorrect(opt.label)" name="check_circle" color="green" size="20px" />
          <q-icon v-else name="cancel" color="red" size="20px" />
        </div>
      </div>
    </div>
  </BaseQuestion>
</template>

<script lang="ts">
export default {
  name: 'ChoiceQuestion'
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import type { ExerciseItem } from '../../types'
import { useMessageRenderer } from '../../composables/useMessageRenderer'
import BaseQuestion from './BaseQuestion.vue'

const props = defineProps<{
  question: ExerciseItem
  modelValue?: string[]
  showTitle?: boolean
  showAnalysis?: boolean
  disabled?: boolean
}>()

const emit = defineEmits(['update:modelValue', 'change'])

const { renderMessageContent } = useMessageRenderer()

const options = computed(() => props.question.structuredContent?.options || [])

const isSelected = (label: string) => props.modelValue?.includes(label)
const isCorrect = (label: string) => {
  const answer = props.question.answer
  if (Array.isArray(answer)) {
    return answer.includes(label)
  }
  // 某些情况下后端可能返回 "C,D" 格式
  if (typeof answer === 'string' && answer.includes(',')) {
    return answer.split(',').map((s) => s.trim()).includes(label)
  }
  return answer === label
}

const handleSelect = (label: string) => {
  if (props.disabled) return // 禁用交互

  let newValue = [...(props.modelValue || [])]
  const index = newValue.indexOf(label)
  if (index > -1) {
    newValue.splice(index, 1)
  } else {
    // 判断是否为多选题
    const isMultiple =
      props.question.type === 'multiple_choice' ||
      props.question.structuredContent?.type === 'multiple_choice'

    if (isMultiple) {
      newValue.push(label)
      newValue.sort() // 排序以保持一致性
    } else {
      newValue = [label]
    }
  }
  emit('update:modelValue', newValue)
  emit('change', newValue)
}
</script>

<style scoped>
.choice-options {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.option-item {
  display: flex;
  align-items: center;
  padding: 12px 16px;
  border: 1px solid #eee;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
  gap: 12px;
  position: relative;
}

.option-item:hover:not(.selected) {
  background: #f9f9ff;
  border-color: #615efe;
}

.option-item.selected {
  background: #f0f0ff;
  border-color: #615efe;
}

.option-label {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  border: 1px solid #ddd;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  color: #666;
  flex-shrink: 0;
}

.option-item.selected .option-label {
  background: #615efe;
  color: white;
  border-color: #615efe;
}

.option-text {
  flex: 1;
  font-size: 15px;
}

.option-status-icon {
  width: 20px;
  height: 20px;
}

.option-item.correct {
  border-color: #22c55e;
  background: #f0fff4;
}

.option-item.correct .option-label {
  background: #22c55e;
  border-color: #22c55e;
  color: white;
}

.option-item.wrong {
  border-color: #ef4444;
  background: #fef2f2;
}

.option-item.wrong .option-label {
  background: #ef4444;
  border-color: #ef4444;
  color: white;
}
</style>

// imates-react/src/components/exercise/ChoiceQuestion.tsx
import React, { useMemo, useCallback } from 'react'
import { BaseQuestion, type ExerciseItem } from '@/components/exercise/BaseQuestion'
import { useMessageRenderer } from '@/hooks/useMessageRenderer'
import '@/components/exercise/ChoiceQuestion.css'

export interface ChoiceQuestionProps {
  question: ExerciseItem
  value?: string[]
  showTitle?: boolean
  showId?: boolean
  showAnalysis?: boolean
  disabled?: boolean
  onChange?: (value: string[]) => void
}

export const ChoiceQuestion: React.FC<ChoiceQuestionProps> = ({
  question,
  value = [],
  showTitle = false,
  showId = true,
  showAnalysis = false,
  disabled = false,
  onChange,
}) => {
  const { renderMessageContent } = useMessageRenderer()

  const options = useMemo(() => {
    return (question.structuredContent as any)?.options || []
  }, [question])

  const isSelected = useCallback((label: string) => value.includes(label), [value])

  const isCorrect = useCallback((label: string) => {
    const answer = question.answer
    if (Array.isArray(answer)) {
      return answer.includes(label)
    }
    // 某些情况下后端可能返回 "C,D" 格式
    if (typeof answer === 'string' && answer.includes(',')) {
      return answer.split(',').map((s: string) => s.trim()).includes(label)
    }
    return answer === label
  }, [question.answer])

  const handleSelect = (label: string) => {
    if (disabled) return
    
    let newSelected = [...value]
    const index = newSelected.indexOf(label)
    
    if (index > -1) {
      newSelected.splice(index, 1)
    } else {
      // 判断是否为多选题
      const isMultiple =
        question.type === 'multiple_choice' ||
        (question.structuredContent as any)?.type === 'multiple_choice'

      if (isMultiple) {
        newSelected.push(label)
        newSelected.sort() // 排序以保持一致性
      } else {
        newSelected = [label]
      }
    }
    
    onChange?.(newSelected)
  }

  return (
    <BaseQuestion 
      question={question} 
      showTitle={showTitle} 
      showId={showId} 
      showAnalysis={showAnalysis}
    >
      <div className="choice-options">
        {options.map((opt: any) => (
          <div 
            key={opt.label}
            className={`option-item ${isSelected(opt.label) ? 'selected' : ''} ${
              disabled && isSelected(opt.label) 
                ? (isCorrect(opt.label) ? 'correct' : 'wrong') 
                : ''
            }`}
            onClick={() => handleSelect(opt.label)}
          >
            <div className="option-label">{opt.label}</div>
            <div className="option-text" dangerouslySetInnerHTML={{ __html: renderMessageContent(opt.text || '') }} />
            {disabled && isSelected(opt.label) && (
              <div className="option-status-icon">
                {isCorrect(opt.label) ? (
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="#22c55e">
                    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
                  </svg>
                ) : (
                  <svg viewBox="0 0 24 24" width="20" height="20" fill="#ef4444">
                    <path d="M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm5 13.59L15.59 17 12 13.41 8.41 17 7 15.59 10.59 12 7 8.41 8.41 7 12 10.59 15.59 7 17 8.41 13.41 12 17 15.59z"/>
                  </svg>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    </BaseQuestion>
  )
}

export default ChoiceQuestion
