// imates-web/src/components/dialog/ImageProcessorDialog.vue
<template>
  <Modal
    v-model="localVisible"
    title="你想问什么问题呢？"
    :initial-width="900"
    :initial-height="900"
    :min-width="500"
    :min-height="450"
    :z-index="screenshotDialogZIndex"
    :close-on-overlay-click="false"
    title-align="left"
    header-background-color="#ffffff"
    :show-footer="true"
    :confirm-text="'给学伴'"
    @confirm="handleConfirm"
    @cancel="handleCancel"
  >
    <!-- 调试按钮 -->
    <template #header-right>
      <q-btn flat round dense icon="bug_report" color="primary" @click="handleDebugLog">
        <q-tooltip>打印调试数据</q-tooltip>
      </q-btn>
    </template>
    <div class="screenshot-input-body">
      <!-- 左侧：截图编辑区域（集成 drawingBoardNew） -->
      <div class="screenshot-editor">
        <drawingBoardNew
          v-if="previewImage"
          key="drawing-mode"
          ref="drawingBoardRef"
          :background-image="previewImage"
          :show-toolbar="!isCropping"
          :show-zoom-controls="false"
          :enable-buffer="false"
          :tools="['undo', 'redo', 'clear', 'draw', 'crop']"
          :force-pen-color="'red'"
          background-position="center"
          :background-contain="true"
          :show-grid="false"
          :allow-popup="false"
          toolbar-position="bottom"
          @tool-change="(tool: string) => {
              console.log('[ScreenshotDialog] drawingBoardNew @tool-change:', tool);
              if (tool === 'crop') isCropping = true;
            }"
        >
          <!-- 将 ImageCropOverlay 作为 drawingBoardNew 的一个层注入 -->
          <template #overlay>
            <ImageCropOverlay
              v-if="isCropping"
              v-model="isCropping"
              :image-src="getOriginalImage()"
              :show-info="false"
              :is-inline="true"
              @confirm="handleCropConfirm"
              @cancel="isCropping = false"
            />
          </template>
        </drawingBoardNew>
        <div v-else class="empty-placeholder">
          <q-icon name="image" size="48px" color="grey-5" />
          <span>暂无截图</span>
        </div>
      </div>
      <!-- 右侧：截图缩略图列表 + 继续截图按钮（竖直排列，仅多截图模式下显示） -->
      <div v-if="props.mode === 'multiple'" class="screenshot-side-panel">
        <div class="side-panel-body">
          <div v-if="thumbnailList.length" class="side-thumbs-list">
            <ScreenshotThumb
              v-for="shot in thumbnailList"
              :key="shot.id"
              :image-url="shot.dataUrl"
              :active="shot.id === currentShotId"
              :show-delete="true"
              @click="switchPreview(shot.id)"
              @remove="handleRemoveThumbnail(shot.id)"
            />
          </div>
          <div v-else class="side-empty-text">暂无可用截图</div>
        </div>
        <div class="side-panel-footer" v-if="thumbnailList.length < MAX_SCREENSHOTS">
          <button
            type="button"
            class="add-more-btn"
            :disabled="!currentShotId"
            @click.stop.prevent="handleAddMore"
          >
            +
          </button>
        </div>
      </div>
    </div>
  </Modal>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick, type ComponentPublicInstance } from 'vue'
import Modal from '@/components/base/Modal.vue'
import drawingBoardNew from '@/components/drawing/drawingBoardNew.vue'
import ImageCropOverlay from '@/components/base/ImageCropper.vue'
import ScreenshotThumb from '@/components/display/ScreenshotThumb.vue'
import { showMessage } from '@/utils'
import type { AttachedScreenshot } from '@/types'
import type { ExerciseSession } from '@/stores/aiExerciseChatStore'

const screenshotDialogZIndex = 14000

// 最多允许挂载的截图数量
const MAX_SCREENSHOTS = 3

// drawingBoardNew 暴露的方法类型
interface DrawingBoardExposed {
  exportToJpg: (quality?: number) => string
  clearAll: () => void
  saveData: () => any
  loadData: (data: any) => void
}

interface ScreenshotDrawingState {
  objects: any[]
  history: any[][]
  historyIndex: number
}
interface Props {
  modelValue: boolean // 是否显示对话框（由 v-model 控制）
  mode?: 'single' | 'multiple' // 截图输入对话框工作模式，'single'=一张，'multiple'=多张(默认)
  initialShotId?: string // 打开时优先选中的截图（用于编辑已挂载截图）
  existingScreenshots?: AttachedScreenshot[] // 右侧缩略图列表，支持多图切换（父组件传入）
  drawingStatesFromParent?: Record<string, ScreenshotDrawingState> // 恢复每张图的绘图状态（标注/擦除历史，父组件传入）
}

interface Emits {
  (e: 'update:modelValue', value: boolean): void
  (
    e: 'confirm',
    screenshots: AttachedScreenshot[],
    states: Record<string, ScreenshotDrawingState>
  ): void
  (
    e: 'add-more',
    screenshots: AttachedScreenshot[],
    states: Record<string, ScreenshotDrawingState>
  ): void
  (e: 'cancel'): void
  (e: 'remove-screenshot', id: string): void
}

const props = withDefaults(defineProps<Props>(), {
  initialShotId: '',
  existingScreenshots: () => [],
  mode: 'multiple',
  drawingStatesFromParent: () => ({}),
})

const emit = defineEmits<Emits>()

// 调试打印函数
const handleDebugLog = () => {
  console.log('=== [ImageProcessorDialog Debug Info] ===')
  console.log('Props:', {
    modelValue: props.modelValue,
    mode: props.mode,
    initialShotId: props.initialShotId,
    existingScreenshots: props.existingScreenshots,
    drawingStatesFromParent: props.drawingStatesFromParent,
  })
  console.log('Local State:', {
    currentShotId: currentShotId.value,
    previewImage: previewImage.value ? previewImage.value.substring(0, 50) + '...' : 'null',
    localScreenshots: localScreenshots.value,
    drawingStates: drawingStates.value,
  })
  console.log('Computed:', {
    thumbnailList: thumbnailList.value,
  })
  console.log('==========================================')
}

// drawingBoardNew 组件引用
const drawingBoardRef = ref<(ComponentPublicInstance & DrawingBoardExposed) | null>(null)

// 当前在画板中预览/编辑的截图 ID
const currentShotId = ref<string | null>(null)

// 当前在画板中预览/编辑的图片（可能是当前截图，也可能是已有截图之一）
const previewImage = ref<string>('')

// 每张截图对应的画板状态（objects + history 等），按截图 ID 索引
const drawingStates = ref<Record<string, ScreenshotDrawingState>>({})

// 本地截图列表，管理所有截图的最新状态（包括编辑后的 dataUrl）
const localScreenshots = ref<AttachedScreenshot[]>([])

const initFromProps = async () => {
  // 先同步父组件传进来的绘图状态
  drawingStates.value = { ...(props.drawingStatesFromParent || {}) }

  // 初始化本地截图列表（从 props 复制，保持独立）
  const list: AttachedScreenshot[] = []
  if (Array.isArray(props.existingScreenshots) && props.existingScreenshots.length > 0) {
    list.push(
      ...props.existingScreenshots.map((s) => ({
        ...s,
        originalDataUrl: s.originalDataUrl || s.dataUrl,
      }))
    )
  }
  localScreenshots.value = list

  // 优先使用 initialShotId，其次使用已有截图列表中的第一张
  const canUseInitialId = !!props.initialShotId && list.some((s) => s.id === props.initialShotId)

  if (canUseInitialId) {
    currentShotId.value = props.initialShotId || null
    previewImage.value = list.find((s) => s.id === props.initialShotId)?.dataUrl || ''
  } else if (list.length > 0) {
    currentShotId.value = list[0].id
    previewImage.value = list[0].dataUrl
  } else {
    currentShotId.value = null
    previewImage.value = ''
  }

  await nextTick()
  const id = currentShotId.value
  const state = id ? drawingStates.value[id] : undefined
  if (id && state && drawingBoardRef.value?.loadData) {
    drawingBoardRef.value.loadData(state)
  } else if (drawingBoardRef.value?.clearAll) {
    drawingBoardRef.value.clearAll()
  }
}

// 弹窗打开时初始化；并在弹窗打开期间，如果父组件更新了截图列表/初始选中/画板状态，也要同步
watch(
  () => [
    props.modelValue,
    props.mode,
    props.initialShotId,
    props.existingScreenshots,
    props.drawingStatesFromParent,
  ],
  async ([visible]) => {
    if (!visible) return
    await initFromProps()
  },
  { immediate: true }
)

// 使用 v-model 的本地状态
const localVisible = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value),
})

// 右侧缩略图数据源：从本地截图列表获取
const thumbnailList = computed(() => localScreenshots.value)

// 获取当前截图的原图数据（用于 DrawingBoard 背景）
const getOriginalImage = () => {
  const currentShot = localScreenshots.value.find((s) => s.id === currentShotId.value)
  // 优先使用原图，如果没有原图则使用当前截图数据
  return currentShot?.originalDataUrl || currentShot?.dataUrl || previewImage.value || ''
}

// 切换预览图片：点击右侧任意缩略图
const switchPreview = async (id: string) => {
  if (!id) return

  const prevId = currentShotId.value

  // 1. 先保存当前截图的画板状态并导出更新后的缩略图
  if (prevId && drawingBoardRef.value) {
    try {
      // 导出当前编辑后的图片（原图+笔记）作为新的缩略图
      if (drawingBoardRef.value.exportToJpg) {
        const exportedImage = drawingBoardRef.value.exportToJpg(0.9)
        // 更新本地截图列表中对应截图的缩略图 dataUrl（原图保持不变）
        const prevShot = localScreenshots.value.find((s) => s.id === prevId)
        if (prevShot && exportedImage) {
          prevShot.dataUrl = exportedImage // 更新缩略图
          // originalDataUrl 保持不变，确保下次编辑时仍使用原图
        }
      }

      // 保存画板状态
      if (drawingBoardRef.value.saveData) {
        const data = drawingBoardRef.value.saveData()
        drawingStates.value[prevId] = {
          objects: data.objects,
          history: data.history,
          historyIndex: data.historyIndex,
        }
      }
    } catch {
      // 静默处理错误，不输出日志
    }
  }

  // 2. 更新当前截图 ID 和预览图片
  currentShotId.value = id
  const target = localScreenshots.value.find((shot) => shot.id === id)
  previewImage.value = target?.dataUrl || ''

  // 3. 加载对应的画板状态：先强制清空画布，再加载新状态
  await nextTick()
  // 先清空画板，避免前一张图的笔迹残留
  if (drawingBoardRef.value?.clearAll) {
    drawingBoardRef.value.clearAll()
  }
  // 再加载新图的状态（如果有）
  const state = drawingStates.value[id]
  if (state && drawingBoardRef.value?.loadData) {
    drawingBoardRef.value.loadData(state)
  }
}

// 删除右侧某个已有截图缩略图
const handleRemoveThumbnail = (id: string) => {
  if (!id) return

  // 从本地截图列表中移除
  const idx = localScreenshots.value.findIndex((s) => s.id === id)
  if (idx >= 0) {
    localScreenshots.value.splice(idx, 1)
  }

  // 移除本地缓存的画板状态
  if (drawingStates.value[id]) {
    delete drawingStates.value[id]
  }

  // 如果删除的是当前正在编辑的截图，重置当前预览并清空画板
  if (currentShotId.value === id) {
    currentShotId.value = null
    previewImage.value = ''
    if (drawingBoardRef.value?.clearAll) {
      drawingBoardRef.value.clearAll()
    }
  }

  emit('remove-screenshot', id)
}

// 将当前截图导出为 AttachedScreenshot 数组
const exportCurrentScreenshot = async (): Promise<AttachedScreenshot[] | null> => {
  // 确保画板状态/画面已渲染到最新（避免导出到旧图）
  await nextTick()

  // 获取当前编辑的截图
  const currentShot = localScreenshots.value.find((s) => s.id === currentShotId.value)
  if (!currentShot) {
    showMessage('截图数据丢失，请重新截图', 'error')
    return null
  }

  // 使用当前截图的 id
  const shotId = currentShotId.value
  if (!shotId) {
    showMessage('截图数据丢失，请重新截图', 'error')
    return null
  }

  // 从 DrawingBoard 导出 JPG 图片（包含背景截图 + 用户标注）
  let finalImageData = previewImage.value || currentShot.dataUrl || ''
  if (drawingBoardRef.value?.exportToJpg) {
    const exportedImage = drawingBoardRef.value.exportToJpg(0.9)
    if (!exportedImage) {
      showMessage('导出截图失败，请稍后重试', 'error')
      return null
    }

    finalImageData = exportedImage
  }

  // 保存当前画板状态到本地 drawingStates
  if (drawingBoardRef.value?.saveData) {
    try {
      const data = drawingBoardRef.value.saveData()
      drawingStates.value[shotId] = {
        objects: data.objects,
        history: data.history,
        historyIndex: data.historyIndex,
      }
    } catch {
      // 静默处理错误
    }
  }

  // 通过 Image 获取宽高
  const size = await new Promise<{ width: number; height: number }>((resolve) => {
    const img = new Image()
    img.onload = () => {
      resolve({ width: img.naturalWidth || img.width, height: img.naturalHeight || img.height })
    }
    img.onerror = () => {
      resolve({ width: 0, height: 0 })
    }
    img.src = finalImageData
  })

  const shot: AttachedScreenshot = {
    id: shotId,
    dataUrl: finalImageData, // 缩略图（原图+笔记）
    originalDataUrl: getOriginalImage(), // 原图数据
    width: size.width,
    height: size.height,
  }

  // 更新当前截图的 dataUrl（保持一致）
  const idx = localScreenshots.value.findIndex((s) => s.id === shotId)
  if (idx >= 0) {
    localScreenshots.value[idx].dataUrl = finalImageData
  }

  return [shot]
}

// 裁剪相关状态
const isCropping = ref(false)

const handleCropConfirm = (croppedDataUrl: string) => {
  console.log('[ScreenshotDialog] handleCropConfirm 收到裁剪后的图片')
  const currentShot = localScreenshots.value.find((s) => s.id === currentShotId.value)
  if (currentShot) {
    // 1. 更新本地数据状态
    currentShot.dataUrl = croppedDataUrl
    previewImage.value = croppedDataUrl

    // 2. 裁剪后清空画板状态，因为参考背景的尺寸变了
    if (currentShotId.value) {
      delete drawingStates.value[currentShotId.value]
    }

    // 3. 强制画板重绘（由于背景图是通过 Prop 传递的，Vue 会响应变化）
    nextTick(async () => {
      if (drawingBoardRef.value?.clearAll) {
        drawingBoardRef.value.clearAll()
      }
    })
  }
  isCropping.value = false
}

// 确定按钮：返回所有截图数组（全量回传）
const handleConfirm = async () => {
  const shots = await exportCurrentScreenshot()
  if (!shots) return

  const current = shots[0]
  const allShots = localScreenshots.value.map((s) => (s.id === current.id ? current : s))

  emit('confirm', allShots, { ...drawingStates.value })
}

// 继续截图：返回所有截图数组并关闭对话框，交给父组件继续触发截图流程
const handleAddMore = async () => {
  // 安全保护：如果当前缩略图数量已达上限，给出提示并中止
  if (localScreenshots.value.length >= MAX_SCREENSHOTS) {
    showMessage(`最多只能添加${MAX_SCREENSHOTS}张截图`, 'warning')
    return
  }

  const shots = await exportCurrentScreenshot()
  if (!shots) return

  const current = shots[0]
  const allShots = localScreenshots.value.map((s) => (s.id === current.id ? current : s))

  emit('add-more', allShots, { ...drawingStates.value })
}

// 取消按钮
const handleCancel = () => {
  emit('cancel')
}
</script>

<style lang="scss" scoped>
.screenshot-input-body {
  display: flex;
  flex-direction: row;
  height: 100%;
  padding: 0 16px 16px 16px;
  gap: 12px;
}

.screenshot-editor {
  flex: 1;
  min-height: 300px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f5f5f5;
  border-radius: 8px;
  border: 1px solid #e0e0e0;
  position: relative;
  overflow: hidden;

  // drawingBoardNew 模式下，Canvas 填满容器
  :deep(.canvas-layer) {
    width: 100% !important;
    height: 100% !important;
    left: 0 !important;
    transform: none !important;
    display: block;
  }

  // 工具栏样式调整（更紧凑）
  :deep(.toolbar-wrapper) {
    top: 8px;
  }

  // 隐藏 DrawingBoard 统一工具栏中的配置按钮
  :deep(.popup-icon-wrapper) {
    display: none !important;
  }

  .empty-placeholder {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 8px;
    color: #9e9e9e;
    font-size: 14px;
  }

  .native-cropper {
    width: 100%;
    height: 100%;
    position: relative;
    overflow: hidden;
    background: #000;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .crop-bg-image {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
    user-select: none;
    -webkit-user-drag: none;
  }

  .crop-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5);
  }

  .crop-window {
    position: absolute;
    border: 2px solid #fff;
    box-shadow: 0 0 0 9999px rgba(0, 0, 0, 0.5);
    cursor: move;
    box-sizing: border-box;

    &::after {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      outline: 1px solid rgba(255, 255, 255, 0.3);
      pointer-events: none;
    }
  }

  .crop-handle {
    position: absolute;
    width: 12px;
    height: 12px;
    background: #fff;
    border: 1px solid #6e55ff;
    border-radius: 2px;
    z-index: 10;

    &.nw {
      top: -6px;
      left: -6px;
      cursor: nw-resize;
    }
    &.ne {
      top: -6px;
      right: -6px;
      cursor: ne-resize;
    }
    &.sw {
      bottom: -6px;
      left: -6px;
      cursor: sw-resize;
    }
    &.se {
      bottom: -6px;
      right: -6px;
      cursor: se-resize;
    }
  }

  .cropper-actions {
    position: absolute;
    bottom: 20px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 100;
    display: flex;
    gap: 12px;
  }
}

.screenshot-side-panel {
  width: 88px;
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  max-height: 95%;
  overflow-y: auto;
  padding: 5px;
}

.side-thumbs-list {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;

  :deep(.screenshot-thumb) {
    width: 72px;
    height: 72px;
    flex-shrink: 0;
  }
}

.side-panel-body {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
}

.side-thumb-wrapper {
  width: 72px;
  height: 72px;
  border-radius: 10px;
  overflow: hidden;
  background: #f5f5f5;
  position: relative;
}

.side-thumb-wrapper--active {
  border-color: #6e55ff;
  box-shadow: 0 0 0 2px rgba(110, 85, 255, 1);
}

.side-thumb-img {
  width: 100%;
  height: 100%;
  object-fit: contain;
  display: block;
}

.side-thumb-close {
  position: absolute;
  top: 4px;
  right: 4px;
  width: 18px;
  height: 18px;
  border-radius: 50%;
  border: none;
  padding: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(0, 0, 0, 0.5);
  cursor: pointer;
}

.side-thumb-close:hover {
  background: rgba(0, 0, 0, 0.7);
}

.side-empty-text {
  font-size: 12px;
  color: #9e9e9e;
}

.side-panel-footer {
  display: flex;
  justify-content: center;
  width: 100%;
}

.add-more-btn {
  width: 72px;
  height: 72px;
  border-radius: 10px;
  border: 1px dashed #c2c2d6;
  background-color: transparent;
  color: #c2c2d6;
  font-size: 32px;
  line-height: 1;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;

  &:hover:not(:disabled) {
    border-color: #6e55ff;
    color: #6e55ff;
    background-color: rgba(110, 85, 255, 0.04);
  }

  &:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }
}
</style>

// imates-react/src/components/dialog/ImageProcessorDialog.tsx
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import Modal from '@/components/base/Modal'
import DrawingBoard from '@/components/drawing/DrawingBoard'
import ImageCropper from '@/components/base/ImageCropper'
import ScreenshotThumb from '@/components/display/ScreenshotThumb'
import { showMessage } from '@/utils'
import type { AttachedScreenshot } from '@/types'
import '@/components/dialog/ImageProcessorDialog.css'

interface ScreenshotDrawingState {
  objects: any[]
  history: any[][]
  historyIndex: number
}

interface ImageProcessorDialogProps {
  open: boolean
  mode?: 'single' | 'multiple'
  initialShotId?: string
  existingScreenshots?: AttachedScreenshot[]
  drawingStatesFromParent?: Record<string, ScreenshotDrawingState>
  onConfirm?: (screenshots: AttachedScreenshot[], states: Record<string, ScreenshotDrawingState>) => void
  onAddMore?: (screenshots: AttachedScreenshot[], states: Record<string, ScreenshotDrawingState>) => void
  onCancel?: () => void
  onRemoveScreenshot?: (id: string) => void
  onClose?: () => void
}

const MAX_SCREENSHOTS = 3

export const ImageProcessorDialog: React.FC<ImageProcessorDialogProps> = ({
  open,
  mode = 'multiple',
  initialShotId = '',
  existingScreenshots = [],
  drawingStatesFromParent = {},
  onConfirm,
  onAddMore,
  onCancel,
  onRemoveScreenshot,
  onClose,
}) => {
  const [currentShotId, setCurrentShotId] = useState<string | null>(null)
  const [previewImage, setPreviewImage] = useState<string>('')
  const [drawingStates, setDrawingStates] = useState<Record<string, ScreenshotDrawingState>>({})
  const [localScreenshots, setLocalScreenshots] = useState<AttachedScreenshot[]>([])
  const [isCropping, setIsCropping] = useState(false)
  
  const drawingBoardRef = useRef<any>(null)

  // 初始化逻辑
  useEffect(() => {
    if (!open) return

    setDrawingStates({ ...drawingStatesFromParent })
    
    const list = existingScreenshots.map(s => ({
      ...s,
      originalDataUrl: s.originalDataUrl || s.dataUrl
    }))
    setLocalScreenshots(list)

    const canUseInitialId = !!initialShotId && list.some(s => s.id === initialShotId)
    if (canUseInitialId) {
      setCurrentShotId(initialShotId)
      setPreviewImage(list.find(s => s.id === initialShotId)?.dataUrl || '')
    } else if (list.length > 0) {
      setCurrentShotId(list[0].id)
      setPreviewImage(list[0].dataUrl)
    } else {
      setCurrentShotId(null)
      setPreviewImage('')
    }
  }, [open, initialShotId, existingScreenshots, drawingStatesFromParent])

  // 加载画板数据
  useEffect(() => {
    if (currentShotId && drawingBoardRef.current) {
      const state = drawingStates[currentShotId]
      if (state && typeof drawingBoardRef.current.loadData === 'function') {
        drawingBoardRef.current.loadData(state)
      } else if (typeof drawingBoardRef.current.clearAll === 'function') {
        drawingBoardRef.current.clearAll()
      }
    }
  }, [currentShotId, drawingStates])

  const getOriginalImage = useCallback(() => {
    const currentShot = localScreenshots.find(s => s.id === currentShotId)
    return currentShot?.originalDataUrl || currentShot?.dataUrl || previewImage || ''
  }, [localScreenshots, currentShotId, previewImage])

  const saveCurrentState = useCallback(() => {
    if (!currentShotId || !drawingBoardRef.current) return

    try {
      if (typeof drawingBoardRef.current.saveData === 'function') {
        const data = drawingBoardRef.current.saveData()
        setDrawingStates(prev => ({
          ...prev,
          [currentShotId]: {
            objects: data.objects,
            history: data.history,
            historyIndex: data.historyIndex,
          }
        }))
      }

      if (typeof drawingBoardRef.current.exportToJpg === 'function') {
        const exportedImage = drawingBoardRef.current.exportToJpg(0.9)
        if (exportedImage) {
          setLocalScreenshots(prev => prev.map(s => 
            s.id === currentShotId ? { ...s, dataUrl: exportedImage } : s
          ))
        }
      }
    } catch (e) {
      console.warn('[ImageProcessorDialog] Save state failed:', e)
    }
  }, [currentShotId])

  const switchPreview = (id: string) => {
    if (id === currentShotId) return
    saveCurrentState()
    setCurrentShotId(id)
    const target = localScreenshots.find(s => s.id === id)
    setPreviewImage(target?.dataUrl || '')
  }

  const handleRemoveThumbnail = (id: string) => {
    setLocalScreenshots(prev => prev.filter(s => s.id !== id))
    setDrawingStates(prev => {
      const next = { ...prev }
      delete next[id]
      return next
    })

    if (currentShotId === id) {
      setCurrentShotId(null)
      setPreviewImage('')
    }
    onRemoveScreenshot?.(id)
  }

  const exportCurrentScreenshot = async (): Promise<AttachedScreenshot[] | null> => {
    if (!currentShotId) return null
    
    const currentShot = localScreenshots.find(s => s.id === currentShotId)
    if (!currentShot) {
      showMessage('截图数据丢失，请重新截图', 'error')
      return null
    }

    let finalImageData = previewImage || currentShot.dataUrl || ''
    if (drawingBoardRef.current && typeof drawingBoardRef.current.exportToJpg === 'function') {
      const exported = drawingBoardRef.current.exportToJpg(0.9)
      if (exported) finalImageData = exported
    }

    // 更新状态
    saveCurrentState()

    const size = await new Promise<{ width: number; height: number }>((resolve) => {
      const img = new Image()
      img.onload = () => resolve({ width: img.naturalWidth || img.width, height: img.naturalHeight || img.height })
      img.onerror = () => resolve({ width: 0, height: 0 })
      img.src = finalImageData
    })

    const shot: AttachedScreenshot = {
      id: currentShotId,
      dataUrl: finalImageData,
      originalDataUrl: getOriginalImage(),
      width: size.width,
      height: size.height,
    }

    return [shot]
  }

  const handleConfirm = async () => {
    const shots = await exportCurrentScreenshot()
    if (!shots) return

    const current = shots[0]
    const allShots = localScreenshots.map(s => (s.id === current.id ? current : s))
    onConfirm?.(allShots, drawingStates)
    onClose?.()
  }

  const handleAddMore = async () => {
    if (localScreenshots.length >= MAX_SCREENSHOTS) {
      showMessage(`最多只能添加${MAX_SCREENSHOTS}张截图`, 'warning')
      return
    }

    const shots = await exportCurrentScreenshot()
    if (!shots) return

    const current = shots[0]
    const allShots = localScreenshots.map(s => (s.id === current.id ? current : s))
    onAddMore?.(allShots, drawingStates)
  }

  const handleCropConfirm = (croppedDataUrl: string) => {
    setLocalScreenshots(prev => prev.map(s => 
      s.id === currentShotId ? { ...s, dataUrl: croppedDataUrl } : s
    ))
    setPreviewImage(croppedDataUrl)
    if (currentShotId) {
      setDrawingStates(prev => {
        const next = { ...prev }
        delete next[currentShotId]
        return next
      })
    }
    setIsCropping(false)
  }

  const handleCancel = () => {
    onCancel?.()
    onClose?.()
  }

  return (
    <Modal
      open={open}
      title="你想问什么问题呢？"
      width={900}
      height={700}
      confirmText="给学伴"
      onConfirm={handleConfirm}
      onCancel={handleCancel}
      onClose={onClose}
    >
      <div className="screenshot-input-body">
        <div className="screenshot-editor">
          {previewImage ? (
            <DrawingBoard
              key={currentShotId}
              ref={drawingBoardRef}
              backgroundColor="transparent"
              onToolChange={(tool) => {
                if (tool === 'crop') setIsCropping(true)
              }}
            >
              {isCropping && (
                <ImageCropper
                  open={isCropping}
                  src={getOriginalImage()}
                  isInline={true}
                  showInfo={false}
                  onConfirm={handleCropConfirm}
                  onCancel={() => setIsCropping(false)}
                />
              )}
            </DrawingBoard>
          ) : (
            <div className="empty-placeholder">
              <span>暂无截图</span>
            </div>
          )}
        </div>

        {mode === 'multiple' && (
          <div className="screenshot-side-panel">
            <div className="side-panel-body">
              {localScreenshots.length > 0 ? (
                <div className="side-thumbs-list">
                  {localScreenshots.map(shot => (
                    <ScreenshotThumb
                      key={shot.id}
                      imageUrl={shot.dataUrl}
                      active={shot.id === currentShotId}
                      showDelete={true}
                      onClick={() => switchPreview(shot.id)}
                      onRemove={() => handleRemoveThumbnail(shot.id)}
                    />
                  ))}
                </div>
              ) : (
                <div className="side-empty-text">暂无可用截图</div>
              )}
            </div>
            {localScreenshots.length < MAX_SCREENSHOTS && (
              <div className="side-panel-footer">
                <button
                  type="button"
                  className="add-more-btn"
                  disabled={!currentShotId}
                  onClick={handleAddMore}
                >
                  +
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </Modal>
  )
}

export default ImageProcessorDialog
