// imates-react/src/components/display/ImageViewer.tsx
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import ReactDOM from 'react-dom'
import downloadIcon from '/icons/download.svg'
import { androidBridge } from '@/services/business/android-bridge'
import { showMessage } from '@/utils'
import '@/components/display/ImageViewer.css'

interface ImageItem {
  url: string
  alt?: string
}

interface ImageViewerProps {
  open: boolean
  onClose: () => void
  imageUrl?: string
  alt?: string
  images?: ImageItem[]
  initialIndex?: number
  onChange?: (index: number) => void
}

type Point = { x: number; y: number }

export const ImageViewer: React.FC<ImageViewerProps> = ({
  open,
  onClose,
  imageUrl = '',
  alt = '图片预览',
  images = [],
  initialIndex = 0,
  onChange,
}) => {
  const [currentIndex, setCurrentIndex] = useState(initialIndex)
  const [translateX, setTranslateX] = useState(0)
  const [translateY, setTranslateY] = useState(0)
  const [scale, setScale] = useState(1)
  const [rotationDeg, setRotationDeg] = useState(0)
  const [enableTransition, setEnableTransition] = useState(false)

  const previewContentRef = useRef<HTMLDivElement>(null)
  const activePointers = useRef(new Map<number, Point>())
  const lastSinglePointer = useRef<{ id: number; x: number; y: number } | null>(null)
  const gestureStart = useRef<{
    distance: number
    angleDeg: number
    midpoint: Point
    startScale: number
    startRotationDeg: number
    startTranslateX: number
    startTranslateY: number
  } | null>(null)

  const MIN_SCALE = 0.5
  const MAX_SCALE = 5
  const ROTATION_THRESHOLD = 7

  useEffect(() => {
    if (open) {
      setCurrentIndex(initialIndex)
      resetTransform()
    }
  }, [open, initialIndex])

  const resetTransform = useCallback(() => {
    setTranslateX(0)
    setTranslateY(0)
    setScale(1)
    setRotationDeg(0)
    setEnableTransition(false)
    activePointers.current.clear()
    gestureStart.current = null
  }, [])

  useEffect(() => {
    resetTransform()
  }, [currentIndex, imageUrl, resetTransform])

  const snapToNearest90 = (deg: number, startDeg: number) => {
    const deltaDeg = deg - startDeg
    const absoluteDelta = Math.abs(deltaDeg)
    if (absoluteDelta <= 30) {
      return startDeg
    } else {
      return Math.round(deg / 90) * 90
    }
  }

  const imageStyle = useMemo(() => {
    const transition = enableTransition ? 'transform 0.3s ease' : 'none'
    return {
      transform: `translate3d(${translateX}px, ${translateY}px, 0) scale(${scale}) rotate(${rotationDeg}deg)`,
      transformOrigin: 'center center',
      transition,
    }
  }, [translateX, translateY, scale, rotationDeg, enableTransition])

  const clamp = (v: number, min: number, max: number) => Math.min(max, Math.max(min, v))
  const getDistance = (a: Point, b: Point) => Math.hypot(a.x - b.x, a.y - b.y)
  const getAngleDeg = (a: Point, b: Point) => (Math.atan2(b.y - a.y, b.x - a.x) * 180) / Math.PI
  const getMidpoint = (a: Point, b: Point): Point => ({ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 })

  const handlePointerDown = (e: React.PointerEvent) => {
    if (!open) return
    e.preventDefault()
    e.stopPropagation()
    setEnableTransition(false)
    activePointers.current.set(e.pointerId, { x: e.clientX, y: e.clientY })

    try {
      (e.target as HTMLElement).setPointerCapture(e.pointerId)
    } catch (err) {}

    if (activePointers.current.size === 1) {
      lastSinglePointer.current = { id: e.pointerId, x: e.clientX, y: e.clientY }
      gestureStart.current = null
    } else if (activePointers.current.size === 2) {
      const pts = Array.from(activePointers.current.values())
      const a = pts[0]
      const b = pts[1]
      gestureStart.current = {
        distance: getDistance(a, b),
        angleDeg: getAngleDeg(a, b),
        midpoint: getMidpoint(a, b),
        startScale: scale,
        startRotationDeg: rotationDeg,
        startTranslateX: translateX,
        startTranslateY: translateY,
      }
      lastSinglePointer.current = null
    }
  }

  const handlePointerMove = (e: React.PointerEvent) => {
    if (!open || !activePointers.current.has(e.pointerId)) return
    e.preventDefault()
    e.stopPropagation()
    activePointers.current.set(e.pointerId, { x: e.clientX, y: e.clientY })

    if (activePointers.current.size === 1 && lastSinglePointer.current?.id === e.pointerId) {
      const dx = e.clientX - lastSinglePointer.current.x
      const dy = e.clientY - lastSinglePointer.current.y
      setTranslateX(prev => prev + dx)
      setTranslateY(prev => prev + dy)
      lastSinglePointer.current = { id: e.pointerId, x: e.clientX, y: e.clientY }
    } else if (activePointers.current.size >= 2 && gestureStart.current) {
      const pts = Array.from(activePointers.current.values())
      const a = pts[0]
      const b = pts[1]
      const distance = getDistance(a, b)
      const angleDeg = getAngleDeg(a, b)
      const midpoint = getMidpoint(a, b)

      const scaleFactor = gestureStart.current.distance > 0 ? distance / gestureStart.current.distance : 1
      const newScale = clamp(gestureStart.current.startScale * scaleFactor, MIN_SCALE, MAX_SCALE)
      const deltaAngle = angleDeg - gestureStart.current.angleDeg

      let newRotation = rotationDeg
      if (Math.abs(deltaAngle) > ROTATION_THRESHOLD) {
        newRotation = gestureStart.current.startRotationDeg + deltaAngle
      }

      const containerRect = previewContentRef.current?.getBoundingClientRect()
      if (containerRect) {
        const centerX = containerRect.left + containerRect.width / 2
        const centerY = containerRect.top + containerRect.height / 2
        const scaleRatio = newScale / gestureStart.current.startScale
        const startRelativeX = gestureStart.current.midpoint.x - centerX - gestureStart.current.startTranslateX
        const startRelativeY = gestureStart.current.midpoint.y - centerY - gestureStart.current.startTranslateY

        setTranslateX(midpoint.x - centerX - startRelativeX * scaleRatio)
        setTranslateY(midpoint.y - centerY - startRelativeY * scaleRatio)
        setScale(newScale)
        setRotationDeg(newRotation)
      }
    }
  }

  const handlePointerUp = (e: React.PointerEvent) => {
    if (!activePointers.current.has(e.pointerId)) return
    e.preventDefault()
    e.stopPropagation()
    activePointers.current.delete(e.pointerId)

    try {
      (e.target as HTMLElement).releasePointerCapture(e.pointerId)
    } catch (err) {}

    if (activePointers.current.size === 1) {
      const remainingId = Array.from(activePointers.current.keys())[0]
      const pt = activePointers.current.get(remainingId)
      if (pt) {
        lastSinglePointer.current = { id: remainingId, x: pt.x, y: pt.y }
      }
      gestureStart.current = null
    } else if (activePointers.current.size < 1) {
      const startRotationDeg = gestureStart.current?.startRotationDeg || 0
      lastSinglePointer.current = null
      gestureStart.current = null

      const snappedRotation = snapToNearest90(rotationDeg, startRotationDeg)
      if (snappedRotation !== rotationDeg) {
        setEnableTransition(true)
        setRotationDeg(snappedRotation)
        setTimeout(() => setEnableTransition(false), 300)
      }
    }
  }

  const currentImageUrl = images.length > 0 ? images[currentIndex]?.url : imageUrl
  const currentAlt = images.length > 0 ? images[currentIndex]?.alt || alt : alt
  const totalImages = images.length > 0 ? images.length : 1
  const showPrev = images.length > 1 && currentIndex > 0
  const showNext = images.length > 1 && currentIndex < images.length - 1

  const handlePrev = () => {
    if (currentIndex > 0) {
      const next = currentIndex - 1
      setCurrentIndex(next)
      onChange?.(next)
    }
  }

  const handleNext = () => {
    if (currentIndex < images.length - 1) {
      const next = currentIndex + 1
      setCurrentIndex(next)
      onChange?.(next)
    }
  }

  const handleClose = () => {
    onClose()
    resetTransform()
  }

  const getExtFromDataUrl = (dataUrl: string) => {
    const match = dataUrl.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,/)
    if (!match) return 'png'
    const mime = match[1]
    const ext = mime.split('/')[1]
    return ext || 'png'
  }

  const dataUrlToBlob = (dataUrl: string) => {
    const commaIndex = dataUrl.indexOf(',')
    if (commaIndex < 0) throw new Error('invalid data url')
    const base64 = dataUrl.slice(commaIndex + 1)
    const mimeMatch = dataUrl.slice(0, commaIndex).match(/^data:([^;]+);base64$/)
    const mime = mimeMatch?.[1] || 'application/octet-stream'
    const binary = atob(base64)
    const len = binary.length
    const bytes = new Uint8Array(len)
    for (let i = 0; i < len; i++) bytes[i] = binary.charCodeAt(i)
    return new Blob([bytes], { type: mime })
  }

  const blobToDataUrl = (blob: Blob) => {
    return new Promise<string>((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = () => resolve(String(reader.result || ''))
      reader.onerror = () => reject(new Error('read blob failed'))
      reader.readAsDataURL(blob)
    })
  }

  const downloadBlob = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob)
    try {
      const a = document.createElement('a')
      a.href = url
      a.download = filename
      a.rel = 'noopener'
      document.body.appendChild(a)
      a.click()
      a.remove()
    } finally {
      URL.revokeObjectURL(url)
    }
  }

  const fetchAsBlob = async (url: string) => {
    const resp = await fetch(url)
    if (!resp.ok) {
      throw new Error(`fetch failed: ${resp.status}`)
    }
    return await resp.blob()
  }

  const handleSave = async () => {
    if (!currentImageUrl) return
    try {
      if (androidBridge.isAndroidBridgeAvailable() && androidBridge.saveBase64ImageToGallery) {
        let dataUrl = currentImageUrl
        if (!dataUrl.startsWith('data:image/')) {
          try {
            const blob = await fetchAsBlob(currentImageUrl)
            dataUrl = await blobToDataUrl(blob)
          } catch (fetchErr) {
            console.warn('[ImageViewer] fetch failed, falling back to window.open:', fetchErr)
            window.open(currentImageUrl, '_blank', 'noopener')
            showMessage('已在新窗口打开，请长按/右键保存', 'info')
            return
          }
        }
        const ext = getExtFromDataUrl(dataUrl)
        const filename = `image_${Date.now()}.${ext}`
        const result = androidBridge.saveBase64ImageToGallery(dataUrl, filename)
        if (result?.success) {
          showMessage('已保存到相册', 'success')
          return
        }
      }

      if (currentImageUrl.startsWith('data:image/')) {
        const ext = getExtFromDataUrl(currentImageUrl)
        const filename = `image_${Date.now()}.${ext}`
        downloadBlob(dataUrlToBlob(currentImageUrl), filename)
        showMessage('开始下载', 'success')
        return
      }

      try {
        const blob = await fetchAsBlob(currentImageUrl)
        const type = blob.type || ''
        const ext = type.startsWith('image/') ? type.split('/')[1] : 'png'
        const filename = `image_${Date.now()}.${ext}`
        downloadBlob(blob, filename)
        showMessage('开始下载', 'success')
      } catch (fetchErr) {
        console.warn('[ImageViewer] fetch failed, falling back to window.open:', fetchErr)
        window.open(currentImageUrl, '_blank', 'noopener')
        showMessage('已在新窗口打开，请长按/右键保存', 'info')
      }
    } catch (err) {
      console.error('[ImageViewer] 保存失败:', err)
      try {
        window.open(currentImageUrl, '_blank', 'noopener')
        showMessage('已在新窗口打开，请长按/右键保存', 'info')
      } catch (e) {
        showMessage('保存失败', 'error')
      }
    }
  }

  useEffect(() => {
    const handleKeydown = (e: KeyboardEvent) => {
      if (!open) return
      if (e.key === 'ArrowLeft') handlePrev()
      else if (e.key === 'ArrowRight') handleNext()
      else if (e.key === 'Escape') handleClose()
    }
    window.addEventListener('keydown', handleKeydown)
    return () => window.removeEventListener('keydown', handleKeydown)
  }, [open, currentIndex, images.length])

  if (!open) return null

  return ReactDOM.createPortal(
    <div className="image-viewer-root">
      <div className="preview-overlay" onClick={handleClose}>
        <button type="button" className="close-btn" onClick={(e) => { e.stopPropagation(); handleClose(); }}>✕</button>
        <button type="button" className="save-btn" onClick={(e) => { e.stopPropagation(); handleSave(); }} title="保存到本地">
          <img src={downloadIcon} alt="下载" className="save-icon" />
        </button>

        {showPrev && <button type="button" className="nav-btn prev-btn" onClick={(e) => { e.stopPropagation(); handlePrev(); }} title="上一张">‹</button>}
        {showNext && <button type="button" className="nav-btn next-btn" onClick={(e) => { e.stopPropagation(); handleNext(); }} title="下一张">›</button>}

        {totalImages > 1 && <div className="image-counter">{currentIndex + 1} / {totalImages}</div>}

        <div
          ref={previewContentRef}
          className="preview-content"
          onClick={(e) => e.stopPropagation()}
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerCancel={handlePointerUp}
          onPointerLeave={handlePointerUp}
        >
          {currentImageUrl && (
            <img
              src={currentImageUrl}
              alt={currentAlt}
              className="preview-image"
              style={imageStyle}
            />
          )}
        </div>
      </div>
    </div>,
    document.body
  )
}

export default ImageViewer

// imates-web/src/components/ImageViewer.vue
<template>
  <!-- 使用 Teleport 将预览层挂到 body，避免受父级对话框影响 -->
  <Teleport to="body">
    <div v-if="modelValue" class="image-viewer-root">
      <div class="preview-overlay" @click="handleClose">
        <!-- 关闭按钮 -->
        <button
          type="button"
          class="close-btn"
          @click.stop="handleClose"
        >
          ✕
        </button>

        <button
          type="button"
          class="save-btn"
          @click.stop="handleSave"
          title="保存到本地"
        >
          <img :src="downloadIcon" alt="下载" class="save-icon" />
        </button>

        <!-- 上一张按钮 -->
        <button
          v-if="showPrev"
          type="button"
          class="nav-btn prev-btn"
          @click.stop="handlePrev"
          title="上一张"
        >
          ‹
        </button>

        <!-- 下一张按钮 -->
        <button
          v-if="showNext"
          type="button"
          class="nav-btn next-btn"
          @click.stop="handleNext"
          title="下一张"
        >
          ›
        </button>

        <!-- 图片计数器 -->
        <div v-if="totalImages > 1" class="image-counter">
          {{ currentIndex + 1 }} / {{ totalImages }}
        </div>

        <!-- 图片预览区域 -->
        <div class="preview-content" @click.stop>
          <img
            v-if="currentImageUrl"
            :src="currentImageUrl"
            :alt="currentAlt || '图片预览'"
            class="preview-image"
          />
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import downloadIcon from '/icons/download.svg'
import { androidBridge } from '@/services/business/android-bridge'
import { showMessage } from '@/utils'
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'

interface ImageItem {
  url: string
  alt?: string
}

interface Props {
  modelValue: boolean
  imageUrl?: string
  alt?: string
  images?: ImageItem[]
  initialIndex?: number
}

const props = withDefaults(defineProps<Props>(), {
  alt: '图片预览',
  images: () => [],
  initialIndex: 0,
  imageUrl: ''
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  'change': [index: number]
}>()

const currentIndex = ref(props.initialIndex)

// 监听 initialIndex 变化
watch(() => props.initialIndex, (newVal) => {
  currentIndex.value = newVal
})

// 监听 modelValue，打开时重置索引
watch(() => props.modelValue, (newVal) => {
  if (newVal) {
    currentIndex.value = props.initialIndex
  }
})

// 计算属性：是否显示上一张按钮
const showPrev = computed(() => {
  return props.images.length > 1 && currentIndex.value > 0
})

// 计算属性：是否显示下一张按钮
const showNext = computed(() => {
  return props.images.length > 1 && currentIndex.value < props.images.length - 1
})

// 计算属性：当前图片总数
const totalImages = computed(() => {
  return props.images.length > 0 ? props.images.length : 1
})

// 计算属性：当前图片 URL
const currentImageUrl = computed(() => {
  if (props.images.length > 0) {
    return props.images[currentIndex.value]?.url || ''
  }
  return props.imageUrl || ''
})

// 计算属性：当前图片 alt
const currentAlt = computed(() => {
  if (props.images.length > 0) {
    return props.images[currentIndex.value]?.alt || props.alt
  }
  return props.alt
})

// 上一张
const handlePrev = () => {
  if (currentIndex.value > 0) {
    currentIndex.value--
    emit('change', currentIndex.value)
  }
}

// 下一张
const handleNext = () => {
  if (currentIndex.value < props.images.length - 1) {
    currentIndex.value++
    emit('change', currentIndex.value)
  }
}

// 键盘事件处理
const handleKeydown = (e: KeyboardEvent) => {
  if (!props.modelValue) return
  if (e.key === 'ArrowLeft') {
    handlePrev()
  } else if (e.key === 'ArrowRight') {
    handleNext()
  } else if (e.key === 'Escape') {
    handleClose()
  }
}

onMounted(() => {
  window.addEventListener('keydown', handleKeydown)
})

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeydown)
})

const handleClose = () => {
  emit('update:modelValue', false)
}

const getExtFromDataUrl = (dataUrl: string) => {
  const match = dataUrl.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,/)
  if (!match) return 'png'
  const mime = match[1]
  const ext = mime.split('/')[1]
  return ext || 'png'
}

const dataUrlToBlob = (dataUrl: string) => {
  const commaIndex = dataUrl.indexOf(',')
  if (commaIndex < 0) throw new Error('invalid data url')
  const header = dataUrl.slice(0, commaIndex)
  const base64 = dataUrl.slice(commaIndex + 1)
  const mimeMatch = header.match(/^data:([^;]+);base64$/)
  const mime = mimeMatch?.[1] || 'application/octet-stream'
  const binary = atob(base64)
  const len = binary.length
  const bytes = new Uint8Array(len)
  for (let i = 0; i < len; i++) bytes[i] = binary.charCodeAt(i)
  return new Blob([bytes], { type: mime })
}

const blobToDataUrl = (blob: Blob) => {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result || ''))
    reader.onerror = () => reject(new Error('read blob failed'))
    reader.readAsDataURL(blob)
  })
}

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob)
  try {
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.rel = 'noopener'
    document.body.appendChild(a)
    a.click()
    a.remove()
  } finally {
    URL.revokeObjectURL(url)
  }
}

const fetchAsBlob = async (url: string) => {
  const resp = await fetch(url)
  if (!resp.ok) {
    throw new Error(`fetch failed: ${resp.status}`)
  }
  return await resp.blob()
}

const handleSave = async () => {
  const url = currentImageUrl.value
  if (!url) return

  try {
    // Android WebView：优先走原生保存到相册
    if (androidBridge.isAndroidBridgeAvailable() && androidBridge.saveBase64ImageToGallery) {
      let dataUrl = url
      if (!dataUrl.startsWith('data:image/')) {
        try {
          const blob = await fetchAsBlob(url)
          dataUrl = await blobToDataUrl(blob)
        } catch (fetchErr) {
          // fetch 失败（CORS 等），尝试直接在新窗口打开
          console.warn('[ImageViewer] fetch failed, falling back to window.open:', fetchErr)
          window.open(url, '_blank', 'noopener')
          showMessage('已在新窗口打开，请长按/右键保存', 'info')
          return
        }
      }

      const ext = getExtFromDataUrl(dataUrl)
      const filename = `image_${Date.now()}.${ext}`
      const result = androidBridge.saveBase64ImageToGallery(dataUrl, filename)
      if (result?.success) {
        showMessage('已保存到相册', 'success')
        return
      }
      // 原生失败则继续走 Web 下载兜底
    }

    // Web：下载
    if (url.startsWith('data:image/')) {
      const ext = getExtFromDataUrl(url)
      const filename = `image_${Date.now()}.${ext}`
      downloadBlob(dataUrlToBlob(url), filename)
      showMessage('开始下载', 'success')
      return
    }

    try {
      const blob = await fetchAsBlob(url)
      const type = blob.type || ''
      const ext = type.startsWith('image/') ? type.split('/')[1] : 'png'
      const filename = `image_${Date.now()}.${ext}`
      downloadBlob(blob, filename)
      showMessage('开始下载', 'success')
    } catch (fetchErr) {
      // fetch 失败（CORS 等），兜底：直接打开图片地址
      console.warn('[ImageViewer] fetch failed, falling back to window.open:', fetchErr)
      window.open(url, '_blank', 'noopener')
      showMessage('已在新窗口打开，请长按/右键保存', 'info')
    }
  } catch (e) {
    // 兜底：直接打开图片地址
    console.error('[ImageViewer] 保存失败:', e)
    try {
      window.open(url, '_blank', 'noopener')
      showMessage('已在新窗口打开，请长按/右键保存', 'info')
    } catch (err) {
      showMessage('保存失败', 'error')
    }
  }
}
</script>

<style scoped lang="scss">
.image-viewer-root {
  // 确保图片预览层级高于其他自定义对话框（如 Modal，遮罩层 z-index=9000）
  position: fixed;
  inset: 0;
  z-index: var(--z-image-viewer-overlay);
}

.preview-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.95);
  display: flex;
  align-items: center;
  justify-content: center;
  backdrop-filter: blur(10px);
  cursor: pointer;
}

.close-btn {
  position: absolute;
  top: 20px;
  right: 20px;
  z-index: 10;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #ffffff;
  width: 36px;
  height: 36px;
  border-radius: 999px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s ease;
}

.close-btn:hover {
  background: rgba(0, 0, 0, 0.7);
  transform: scale(1.1);
}

.save-btn {
  position: absolute;
  top: 20px;
  right: 68px;
  z-index: 10;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #ffffff;
  height: 36px;
  padding: 0 12px;
  border-radius: 999px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s ease;
}

.save-btn:hover {
  background: rgba(0, 0, 0, 0.7);
  transform: scale(1.05);
}

.save-icon {
  width: 20px;
  height: 20px;
  display: block;
}

/* 导航按钮 */
.nav-btn {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  z-index: 10;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #ffffff;
  width: 48px;
  height: 48px;
  border-radius: 999px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s ease;
  font-size: 24px;
  font-weight: bold;
  padding: 0;
  line-height: 1;
}

.nav-btn:hover {
  background: rgba(0, 0, 0, 0.7);
  transform: translateY(-50%) scale(1.1);
}

.prev-btn {
  left: 20px;
}

.next-btn {
  right: 20px;
}

/* 图片计数器 */
.image-counter {
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 10;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #ffffff;
  padding: 8px 16px;
  border-radius: 999px;
  font-size: 14px;
  font-weight: 500;
}

.preview-content {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 60px 20px 20px;
}

.preview-image {
  max-width: 90vw;
  max-height: 90vh;
  width: auto;
  height: auto;
  object-fit: contain;
  border-radius: 8px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
  user-select: none;
  pointer-events: none;
}
</style>
