// imates-web/src/components/exercise/QuestionAnalysis.vue
<template>
  <div class="question-footer" v-if="show">
    <div class="analysis-section">
      <div class="analysis-block">
        <div class="section-title">参考答案：</div>
        <div
          class="section-content answer-val"
          v-if="formattedAnswer"
          v-html="formattedAnswer"
        ></div>
        <div class="field-missing-warning" v-else>【警告：未配置参考答案】</div>
      </div>
      <div class="analysis-block" style="margin-top: 16px">
        <div class="section-title">题目解析：</div>
        <div
          class="section-content explanation-val"
          v-if="formattedAnalysis"
          v-html="formattedAnalysis"
        ></div>
        <div class="empty-analysis-tip" v-else>暂无解析</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ExerciseItem } from '../../types'
import { useMessageRenderer } from '../../composables/useMessageRenderer'

const props = withDefaults(
  defineProps<{
    question: ExerciseItem
    show?: boolean
  }>(),
  {
    show: false,
  },
)

const { renderMessageContent } = useMessageRenderer()

const formattedAnswer = computed(() => {
  const structured = props.question.structuredContent || props.question
  if (structured?.type === 'fill_in_blank' && Array.isArray(structured.blanks)) {
    const blankAnswers = structured.blanks.map((blank, index) => {
      const ans = Array.isArray(blank.answers) ? blank.answers.join(' 或 ') : blank.answer || ''
      return `(${index + 1}): ${ans}`
    })
    return renderMessageContent(blankAnswers.join('; '))
  }
  const answer = structured?.answer
  if (Array.isArray(answer)) return renderMessageContent(answer.join(', '))
  if (answer === undefined || answer === null) return ''
  return renderMessageContent(String(answer))
})

const formattedAnalysis = computed(() => {
  const q = props.question
  const structured = q.structuredContent

  // 过滤助手：只取 structured?.analysis，如果包含 '###' 标识也一律判定为无效并过滤
  const filterHasHash = (str?: string) => (str && !str.includes('###') ? str : '')

  const rawAnalysis = filterHasHash(structured?.analysis)

  if (!rawAnalysis || !rawAnalysis.trim()) return ''
  return renderMessageContent(rawAnalysis)
})
</script>

<style scoped>
.question-footer {
  margin-top: 24px;
  padding-top: 16px;
}

.analysis-section {
  background-color: #f6f6f6;
  border-radius: 12px;
  padding: 16px;
  margin-bottom: 20px;
}

.section-title {
  font-size: 15px;
  font-weight: 600;
  color: #334155;
  margin-bottom: 8px;
}

.section-content {
  font-size: 15px;
  line-height: 1.6;
}

.section-content.answer-val {
  color: #334155;
}

.field-missing-warning {
  color: #ef4444;
  background-color: #fef2f2;
  border: 1px dashed #fca5a5;
  padding: 8px 12px;
  border-radius: 6px;
  font-size: 13px;
  margin-top: 4px;
  display: block;
  width: fit-content;
}

.empty-analysis-tip {
  color: #94a3b8;
  font-size: 14px;
}

:deep(table) {
  border-collapse: collapse;
  width: 100%;
  margin: 12px 0;
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid #e2e8f0;
}
:deep(th),
:deep(td) {
  border: 1px solid #e2e8f0;
  padding: 8px 12px;
  text-align: left;
}
:deep(th) {
  background-color: #f8fafc;
  font-weight: 600;
  color: #475569;
}
</style>

// imates-app/src/components/exercise/QuestionAnalysis.tsx
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { MathRenderer } from '../MathRenderer';

export interface QuestionAnalysisProps {
  question: any;
  show?: boolean;
}

export function QuestionAnalysis({ question, show = false }: QuestionAnalysisProps) {
  if (!show || !question) return null;

  const structured = question?.structuredContent || question;
  
  // 参考答案提取与格式化
  const rawAnswer = structured?.answer || question?.questionAnswer || '';
  const formattedAnswer = (() => {
    if (structured?.type === 'fill_in_blank' && Array.isArray(structured?.blanks)) {
      return structured.blanks
        .map((b: any, idx: number) => {
          const ansStr = Array.isArray(b.answers) ? b.answers.join(' 或 ') : b.answer || '';
          return `(${idx + 1}): ${ansStr}`;
        })
        .join('; ');
    }
    if (Array.isArray(rawAnswer)) return rawAnswer.join(', ');
    if (rawAnswer === undefined || rawAnswer === null || rawAnswer === '') return '';
    return String(rawAnswer);
  })();

  // 题目解析提取
  const rawAnalysis = (structured?.analysis || question?.questionAnalysis || question?.analysis || '').trim();
  const finalAnalysis = rawAnalysis.includes('###') ? '' : rawAnalysis;

  return (
    <View style={styles.questionFooter}>
      <View style={styles.analysisSection}>
        {/* 参考答案区块 */}
        <View style={styles.analysisBlock}>
          <Text style={styles.sectionTitle}>参考答案：</Text>
          {formattedAnswer ? (
            <View style={styles.sectionContent}>
              <MathRenderer content={formattedAnswer} textColor="#334155" />
            </View>
          ) : (
            <View style={styles.fieldMissingWarning}>
              <Text style={styles.fieldMissingWarningText}>【警告：未配置参考答案】</Text>
            </View>
          )}
        </View>

        {/* 题目解析区块 */}
        <View style={[styles.analysisBlock, { marginTop: 16 }]}>
          <Text style={styles.sectionTitle}>题目解析：</Text>
          {finalAnalysis ? (
            <View style={styles.sectionContent}>
              <MathRenderer content={finalAnalysis} textColor="#334155" />
            </View>
          ) : (
            <Text style={styles.emptyAnalysisTip}>暂无解析</Text>
          )}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  questionFooter: {
    marginTop: 24,
    paddingTop: 16,
  },
  analysisSection: {
    backgroundColor: '#f6f6f6',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  analysisBlock: {
    width: '100%',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#334155',
    marginBottom: 8,
  },
  sectionContent: {
    width: '100%',
  },
  fieldMissingWarning: {
    backgroundColor: '#fef2f2',
    borderColor: '#fca5a5',
    borderWidth: 1,
    borderStyle: 'dashed',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  fieldMissingWarningText: {
    color: '#ef4444',
    fontSize: 13,
  },
  emptyAnalysisTip: {
    color: '#94a3b8',
    fontSize: 14,
  },
});
