// imates-web/src/views/ChatSessionTestView.vue
<template>
  <div class="chat-session-test-view">
    <div class="test-container">
      <h2>CardStack 组件测试</h2>
      
      <div class="component-wrapper">
        <!-- 组件内部已处理卡片宽度，这里只需要让容器 100% 宽度即可 -->
        <CardStack />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import CardStack from '@/components/CardStack.vue'

defineOptions({
  name: 'ChatSessionTestView',
})
</script>

<style scoped>
.chat-session-test-view {
  width: 100%;
  height: 100vh;
  background: #f5f5f5;
  overflow-y: auto;
  padding: 20px;
}

.test-container {
  max-width: 480px;
  margin: 0 auto;
}

h2 {
  margin: 0 0 20px 0;
  color: #333;
  font-size: 24px;
}

.component-wrapper {
  width: 100%;
  height: 600px;
  background: #ffffff;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}
</style>

// imates-react/src/views/testView/ChatSessionTestView.tsx
import React from 'react'
import CardStack from '@/components/base/CardStack'
import './ChatSessionTestView.css'

const ChatSessionTestView: React.FC = () => {
  return (
    <div className="chat-session-test-view">
      <div className="test-container">
        <h2>CardStack 组件测试</h2>
        
        <div className="component-wrapper">
          {/* 组件内部已处理卡片宽度，这里只需要让容器 100% 宽度即可 */}
          <CardStack />
        </div>
      </div>
    </div>
  )
}

export default ChatSessionTestView
