// imates-web/src/views/testView/TestExerciseView.vue
<template>
  <div class="test-exercise-view q-pa-md">
    <h1 class="text-h4 q-mb-lg">题目组件集成测试页面</h1>

    <div class="row q-col-gutter-md">
      <!-- 左侧：测试用例列表 -->
      <div class="col-12 col-md-4">
        <q-list bordered separator class="bg-white rounded-borders">
          <q-item-label header>测试用例</q-item-label>
          <q-item 
            v-for="(item, index) in testQuestions" 
            :key="item.id"
            clickable
            :active="currentIndex === index"
            active-class="bg-primary text-white"
            @click="currentIndex = index"
          >
            <q-item-section>
              <q-item-label>{{ index + 1 }}. {{ item.title }}</q-item-label>
              <q-item-label caption :class="currentIndex === index ? 'text-white' : ''">
                类型: {{ item.question.type }}
              </q-item-label>
            </q-item-section>
          </q-item>
        </q-list>

        <div class="q-mt-md bg-grey-2 q-pa-sm rounded-borders">
          <div class="text-weight-bold">当前实时数据 (v-model):</div>
          <pre class="q-ma-none text-caption">{{ currentAnswer }}</pre>
        </div>
      </div>

      <!-- 右侧：预览与渲染 -->
      <div class="col-12 col-md-8">
        <q-card flat bordered class="full-height">
          <q-toolbar class="bg-grey-1">
            <q-toolbar-title>渲染预览: {{ currentQuestion.title }}</q-toolbar-title>
          </q-toolbar>

          <q-card-section class="q-pa-lg scroll" style="max-height: 70vh">
            <!-- 渲染逻辑分支 -->
             
            <!-- 1. 复合材料题 (Composite) -->
            <div v-if="currentQuestion.question.type === 'composite'" class="composite-container">
              <div class="material-section q-mb-md">
                <div class="text-subtitle1 text-weight-bold">【主题干/材料】</div>
                <div class="q-mt-sm markdown-content" v-html="renderMessageContent(currentQuestion.question.material || '')"></div>
              </div>
              
              <div class="sub-questions-list">
                <div v-for="(sub, sIdx) in currentQuestion.question.subQuestions" :key="sub.id || sIdx" class="sub-question-item q-ml-md q-mt-lg">
                   <!-- 递归渲染或组件分发 -->
                   <div class="text-weight-bold text-primary">子题 ({{ sIdx + 1 }}):</div>
                   
                   <!-- 如果子题还是 composite -->
                   <div v-if="sub.type === 'composite'" class="q-ml-md q-mt-sm">
                      <div class="markdown-content" v-html="renderMessageContent(sub.material || '')"></div>
                      <!-- 继续渲染二级子题 -->
                      <div v-for="(subSub, ssIdx) in sub.subQuestions" :key="subSub.id || ssIdx" class="q-ml-md q-mt-md">
                        <div class="text-weight-bold text-secondary">({{ ssIdx + 1 }})</div>
                        <component 
                          :is="getComponent(subSub.type)" 
                          :question="wrapQuestion(subSub)" 
                          v-model="subSubAnswers[subSub.id]"
                          show-title
                        />
                      </div>
                   </div>

                   <!-- 普通子题 -->
                   <component 
                    v-else
                    :is="getComponent(sub.type)" 
                    :question="wrapQuestion(sub)" 
                    v-model="subAnswers[sub.id]"
                    show-title
                   />
                </div>
              </div>
            </div>

            <!-- 2. 普通题型 -->
            <component 
              v-else
              :is="getComponent(currentQuestion.question.type)" 
              :question="currentQuestion.question" 
              v-model="answers[currentQuestion.id]"
              show-title
            />
          </q-card-section>

          <q-separator />

          <q-card-actions align="right">
            <q-btn flat label="查看解析" color="primary" @click="showAnalysis = true" />
          </q-card-actions>
        </q-card>
      </div>
    </div>

    <!-- 解析对话框 -->
    <q-dialog v-model="showAnalysis">
      <q-card style="min-width: 350px">
        <q-card-section>
          <div class="text-h6">题目解析</div>
        </q-card-section>
        <q-card-section class="q-pt-none markdown-content">
          <div class="text-subtitle2 text-grey-7 q-mb-xs">参考答案:</div>
          <div v-html="renderMessageContent(currentQuestion.question.answer || '无')"></div>
          <q-separator class="q-my-md" />
          <div class="text-subtitle2 text-grey-7 q-mb-xs">详细解析:</div>
          <div v-html="renderMessageContent(currentQuestion.question.analysis || '暂无解析')"></div>
        </q-card-section>
        <q-card-actions align="right">
          <q-btn flat label="关闭" color="primary" v-close-popup />
        </q-card-actions>
      </q-card>
    </q-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, reactive, watch } from 'vue'
import ChoiceQuestion from '@/components/exercise/ChoiceQuestion.vue'
import FillBlankQuestion from '@/components/exercise/FillBlankQuestion.vue'
import JudgmentQuestion from '@/components/exercise/JudgmentQuestion.vue'
import BaseQuestion from '@/components/exercise/BaseQuestion.vue'
import { useMessageRenderer } from '@/composables/useMessageRenderer'

const { renderMessageContent } = useMessageRenderer()

// 测试用例数据
const testQuestions = [
  {
    id: 'test_composite_nested',
    title: '嵌套复合材料题 (用户指定用例)',
    question: {
      "id": "q_1001",
      "subject": "math",
      "score": 5.0,
      "type": "composite",
      "material": "这是主题干",
      "subQuestions": [
        {
          "id": "cq_1",
          "type": "composite",
          "material": "子题干，这题还带两个子题",
          "subQuestions": [
            {
              "id": "cq_2_1",
              "type": "subjective",
              "stem": "第一小题的第一小小题干",
              "answer": "答案for第一小题的第一小小题干",
              "analysis": "解析for第一小题的第一小小题干"
            },
            {
              "id": "cq_2_2",
              "type": "single_choice",
              "stem": "第一小题的第二小小题干",
              "options": [
                {
                  "id": "A",
                  "content": "a选项内容"
                },
                {
                  "id": "B",
                  "content": "b选项内容（设置为正确选项）"
                }
              ],
              "answer": "B"
            }
          ]
        }
      ]
    }
  },
  {
    id: 'test_choice',
    title: '单选题测试',
    question: {
      id: 'q_001',
      type: 'single_choice',
      structuredContent: {
        stem: '1+1 等于几？',
        options: [
          { id: 'A', content: '1' },
          { id: 'B', content: '2' },
          { id: 'C', content: '3' }
        ]
      },
      answer: 'B'
    }
  },
  {
    id: 'test_fill',
    title: '填空题测试',
    question: {
      id: 'q_002',
      type: 'fill_in_blank',
      structuredContent: {
        stem: '床前明月光，[blank_1]，举头望明月，[blank_2]。'
      },
      answer: '疑是地上霜, 低头思故乡'
    }
  }
]

const currentIndex = ref(0)
const currentQuestion = computed(() => testQuestions[currentIndex.value])
const showAnalysis = ref(false)

// 响应式答案存储
const answers = reactive<Record<string, any>>({})
const subAnswers = reactive<Record<string, any>>({})
const subSubAnswers = reactive<Record<string, any>>({})

const currentAnswer = computed(() => {
  const qId = currentQuestion.value.id
  if (currentQuestion.value.question.type === 'composite') {
    return { subAnswers, subSubAnswers }
  }
  return answers[qId]
})

// 组件映射
const getComponent = (type: string) => {
  switch (type) {
    case 'single_choice':
    case 'multiple_choice':
      return ChoiceQuestion
    case 'fill_in_blank':
      return FillBlankQuestion
    case 'true_false':
      return JudgmentQuestion
    default:
      return BaseQuestion
  }
}

// 包装普通子题为组件需要的格式
const wrapQuestion = (sub: any) => {
  if (!sub) return sub
  
  // 提取原始选项数据，支持直接在 sub 下或在 structuredContent 下
  const rawOptions = sub.options || sub.structuredContent?.options || []
  
  // 统一选项格式为 { label, text }，这是系统组件通常期望的格式
  const wrappedOptions = rawOptions.map((opt: any) => ({
    label: opt.id || opt.label, 
    text: opt.content || opt.text 
  }))
  
  const wrapped = {
    ...sub,
    questionContent: sub.stem || sub.questionContent || sub.structuredContent?.stem || '',
    structuredContent: {
      stem: sub.stem || sub.questionContent || sub.structuredContent?.stem || '',
      options: wrappedOptions
    }
  }
  return wrapped
}
</script>

<style scoped>
.test-exercise-view {
  background-color: #f5f5f5;
  min-height: 100vh;
}
.composite-container {
  border-left: 4px solid #1976D2;
  padding-left: 16px;
}
.sub-question-item {
  border-top: 1px dashed #ddd;
  padding-top: 16px;
}
.markdown-content {
  line-height: 1.6;
  font-size: 1.1rem;
}
pre {
  white-space: pre-wrap;
  word-wrap: break-word;
}
</style>

// imates-react/src/views/testView/TestExerciseView.tsx
import React, { useState, useMemo } from 'react'
import ChoiceQuestion from '@/components/exercise/ChoiceQuestion'
import FillBlankQuestion from '@/components/exercise/FillBlankQuestion'
import JudgmentQuestion from '@/components/exercise/JudgmentQuestion'
import BaseQuestion from '@/components/exercise/BaseQuestion'
import { useMessageRenderer } from '@/hooks/useMessageRenderer'
import Button from '@/components/base/Button'
import './TestExerciseView.css'

interface SubQuestion {
  id: string
  type: string
  stem?: string
  questionContent?: string
  structuredContent?: any
  options?: any[]
  material?: string
  subQuestions?: SubQuestion[]
  answer?: string
  analysis?: string
}

interface TestQuestion {
  id: string
  title: string
  question: {
    id: string
    type: string
    material?: string
    subQuestions?: SubQuestion[]
    answer?: string
    analysis?: string
    structuredContent?: any
  }
}

const testQuestions: TestQuestion[] = [
  {
    id: 'test_composite_nested',
    title: '嵌套复合材料题 (用户指定用例)',
    question: {
      "id": "q_1001",
      "type": "composite",
      "material": "这是主题干",
      "subQuestions": [
        {
          "id": "cq_1",
          "type": "composite",
          "material": "子题干，这题还带两个子题",
          "subQuestions": [
            {
              "id": "cq_2_1",
              "type": "subjective",
              "stem": "第一小题的第一小小题干",
              "answer": "答案for第一小题的第一小小题干",
              "analysis": "解析for第一小题的第一小小题干"
            },
            {
              "id": "cq_2_2",
              "type": "single_choice",
              "stem": "第一小题的第二小小题干",
              "options": [
                { "id": "A", "content": "a选项内容" },
                { "id": "B", "content": "b选项内容（设置为正确选项）" }
              ],
              "answer": "B"
            }
          ]
        }
      ]
    }
  },
  {
    id: 'test_choice',
    title: '单选题测试',
    question: {
      id: 'q_001',
      type: 'single_choice',
      structuredContent: {
        stem: '1+1 等于几？',
        options: [
          { id: 'A', content: '1' },
          { id: 'B', content: '2' },
          { id: 'C', content: '3' }
        ]
      },
      answer: 'B'
    }
  },
  {
    id: 'test_fill',
    title: '填空题测试',
    question: {
      id: 'q_002',
      type: 'fill_in_blank',
      structuredContent: {
        stem: '床前明月光，[blank_1]，举头望明月，[blank_2]。'
      },
      answer: '疑是地上霜, 低头思故乡'
    }
  }
]

const TestExerciseView: React.FC = () => {
  const { renderMessageContent } = useMessageRenderer()
  const [currentIndex, setCurrentIndex] = useState(0)
  const [showAnalysis, setShowAnalysis] = useState(false)
  const [answers, setAnswers] = useState<Record<string, any>>({})
  const [subAnswers, setSubAnswers] = useState<Record<string, any>>({})
  const [subSubAnswers, setSubSubAnswers] = useState<Record<string, any>>({})

  const currentQuestion = testQuestions[currentIndex]

  const currentAnswer = useMemo(() => {
    if (currentQuestion.question.type === 'composite') {
      return { subAnswers, subSubAnswers }
    }
    return answers[currentQuestion.id]
  }, [currentQuestion, answers, subAnswers, subSubAnswers])

  const getQuestionComponent = (type: string) => {
    switch (type) {
      case 'single_choice':
      case 'multiple_choice':
        return ChoiceQuestion
      case 'fill_in_blank':
        return FillBlankQuestion
      case 'true_false':
        return JudgmentQuestion
      default:
        return BaseQuestion
    }
  }

  const wrapQuestion = (sub: any) => {
    if (!sub) return sub
    const rawOptions = sub.options || sub.structuredContent?.options || []
    const wrappedOptions = rawOptions.map((opt: any) => ({
      label: opt.id || opt.label,
      text: opt.content || opt.text
    }))
    
    return {
      ...sub,
      questionContent: sub.stem || sub.questionContent || sub.structuredContent?.stem || '',
      structuredContent: {
        stem: sub.stem || sub.questionContent || sub.structuredContent?.stem || '',
        options: wrappedOptions
      }
    }
  }

  const renderQuestion = (q: any, value: any, onChange: (val: any) => void) => {
    const Component = getQuestionComponent(q.type)
    const wrapped = wrapQuestion(q)
    return (
      <Component 
        question={wrapped} 
        value={value} 
        onChange={onChange}
        showTitle={true}
      />
    )
  }

  return (
    <div className="test-exercise-view">
      <h1 className="title-h1">题目组件集成测试页面</h1>

      <div className="test-layout">
        {/* 左侧：测试用例列表 */}
        <div className="test-cases-sidebar">
          <div className="list-container">
            <div className="list-header">测试用例</div>
            {testQuestions.map((item, index) => (
              <div 
                key={item.id}
                className={`list-item ${currentIndex === index ? 'active' : ''}`}
                onClick={() => setCurrentIndex(index)}
              >
                <div>{index + 1}. {item.title}</div>
                <div className="item-caption">
                  类型: {item.question.type}
                </div>
              </div>
            ))}
          </div>

          <div className="real-time-data">
            <div className="data-title">当前实时数据:</div>
            <pre className="data-pre">{JSON.stringify(currentAnswer, null, 2)}</pre>
          </div>
        </div>

        {/* 右侧：预览与渲染 */}
        <div className="preview-main">
          <div className="card">
            <div className="card-toolbar">
              渲染预览: {currentQuestion.title}
            </div>

            <div className="card-content">
              {currentQuestion.question.type === 'composite' ? (
                <div className="composite-container">
                  <div style={{ marginBottom: '16px' }}>
                    <div style={{ fontWeight: 'bold' }}>【主题干/材料】</div>
                    <div 
                      className="markdown-content" 
                      dangerouslySetInnerHTML={{ __html: renderMessageContent(currentQuestion.question.material || '') }}
                    ></div>
                  </div>
                  
                  <div className="sub-questions-list">
                    {currentQuestion.question.subQuestions?.map((sub, sIdx) => (
                      <div key={sub.id || sIdx} className="sub-question-item" style={{ marginLeft: '16px' }}>
                         <div className="text-primary" style={{ fontWeight: 'bold' }}>子题 ({sIdx + 1}):</div>
                         
                         {sub.type === 'composite' ? (
                            <div style={{ marginLeft: '16px', marginTop: '8px' }}>
                               <div 
                                 className="markdown-content" 
                                 dangerouslySetInnerHTML={{ __html: renderMessageContent(sub.material || '') }}
                               ></div>
                               {sub.subQuestions?.map((subSub, ssIdx) => (
                                 <div key={subSub.id || ssIdx} style={{ marginLeft: '16px', marginTop: '16px' }}>
                                   <div className="text-secondary" style={{ fontWeight: 'bold' }}>({ssIdx + 1})</div>
                                   {renderQuestion(
                                      subSub, 
                                      subSubAnswers[subSub.id], 
                                      (val) => setSubSubAnswers(prev => ({ ...prev, [subSub.id]: val }))
                                   )}
                                 </div>
                               ))}
                            </div>
                         ) : (
                            renderQuestion(
                              sub, 
                              subAnswers[sub.id], 
                              (val) => setSubAnswers(prev => ({ ...prev, [sub.id]: val }))
                            )
                         )}
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                renderQuestion(
                  currentQuestion.question, 
                  answers[currentQuestion.id], 
                  (val) => setAnswers(prev => ({ ...prev, [currentQuestion.id]: val }))
                )
              )}
            </div>

            <div className="card-actions">
              <Button label="查看解析" variant="ghost" onClick={() => setShowAnalysis(true)} />
            </div>
          </div>
        </div>
      </div>

      {/* 解析对话框 */}
      {showAnalysis && (
        <div className="dialog-overlay" onClick={() => setShowAnalysis(false)}>
          <div className="dialog-content" onClick={e => e.stopPropagation()}>
            <div className="dialog-header">题目解析</div>
            <div className="dialog-body">
              <div style={{ fontSize: '0.875rem', color: '#777', marginBottom: '4px' }}>参考答案:</div>
              <div 
                className="markdown-content"
                dangerouslySetInnerHTML={{ __html: renderMessageContent(currentQuestion.question.answer || '无') }}
              ></div>
              <hr style={{ margin: '16px 0', border: 'none', borderTop: '1px solid #ddd' }} />
              <div style={{ fontSize: '0.875rem', color: '#777', marginBottom: '4px' }}>详细解析:</div>
              <div 
                className="markdown-content"
                dangerouslySetInnerHTML={{ __html: renderMessageContent(currentQuestion.question.analysis || '暂无解析') }}
              ></div>
            </div>
            <div className="dialog-footer">
              <Button label="关闭" onClick={() => setShowAnalysis(false)} />
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default TestExerciseView
