// imates-app/src/components/exercise/ChoiceQuestion.tsx
import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { BaseQuestion } from './BaseQuestion';
import { QuestionAnalysis } from './QuestionAnalysis';
import { MathRenderer } from '../MathRenderer';

export interface ChoiceOption {
  value: string;
  label: string;
  text: string;
}

export interface ChoiceQuestionProps {
  question: any;
  value?: string[];
  onChange?: (val: string[]) => void;
  showTitle?: boolean;
  showId?: boolean;
  showAnalysis?: boolean;
  disabled?: boolean;
}

export function ChoiceQuestion({
  question,
  value = [],
  onChange,
  showTitle = false,
  showId = false,
  showAnalysis = false,
  disabled = false,
}: ChoiceQuestionProps) {
  // 解析选项 (支持 structuredContent.options, options, questionChooseList, questionChooseInfo)
  const processedOptions: ChoiceOption[] = (() => {
    const rawOptions =
      question?.structuredContent?.options ||
      question?.options ||
      (Array.isArray(question?.questionChooseList) && question.questionChooseList.length > 0 ? question.questionChooseList : []);
    if (Array.isArray(rawOptions) && rawOptions.length > 0) {
      return rawOptions.map((opt: any, idx: number) => {
        const valChar = String(opt.id || opt.label || String.fromCharCode(65 + idx)).trim().toUpperCase();
        const contentText = opt.content || opt.text || (typeof opt === 'string' ? opt : '');
        return {
          value: valChar,
          label: valChar,
          text: contentText,
        };
      });
    }

    // 从 questionChooseInfo 提取 A, B, C, D 选项
    const info = question?.questionChooseInfo;
    if (info) {
      try {
        const parsed = typeof info === 'string' ? JSON.parse(info) : info;
        if (Array.isArray(parsed)) {
          return parsed.map((item: any, idx: number) => {
            const char = String.fromCharCode(65 + idx);
            return { value: char, label: char, text: typeof item === 'string' ? item : (item.text || item.content || char) };
          });
        }
      } catch {
        const parts = String(info).split(/[;；,，]/).map((p: string) => p.trim()).filter(Boolean);
        if (parts.length > 0) {
          return parts.map((p: string, idx: number) => {
            const char = String.fromCharCode(65 + idx);
            return { value: char, label: char, text: p };
          });
        }
      }
    }

    return [];
  })();

  const isMultiple = (question?.structuredContent?.type || question?.type) === 'multiple_choice';

  const isSelected = (val: string) => Array.isArray(value) && value.includes(val);

  const isCorrect = (val: string) => {
    const answer = question?.structuredContent?.answer || question?.questionAnswer || question?.answer;
    if (Array.isArray(answer)) {
      return answer.includes(val);
    }
    return String(answer ?? '') === val;
  };

  const handleSelect = (val: string) => {
    if (disabled) return;
    let newValue = [...(Array.isArray(value) ? value : [])];
    const index = newValue.indexOf(val);
    if (index > -1) {
      newValue.splice(index, 1);
    } else {
      if (isMultiple) {
        newValue.push(val);
        newValue.sort();
      } else {
        newValue = [val];
      }
    }
    if (onChange) onChange(newValue);
  };

  return (
    <BaseQuestion
      question={question}
      showTitle={showTitle}
      showId={showId}
      showTypeTag={true}
    >
      {processedOptions && processedOptions.length > 0 ? (
        <View style={styles.optionsContainer}>
          {processedOptions.map((opt) => {
            const selected = isSelected(opt.value);
            const correct = isCorrect(opt.value);
            const isAnswerState = disabled && selected;

            return (
              <TouchableOpacity
                key={opt.value}
                style={[
                  styles.optionCard,
                  selected && styles.selectedOptionCard,
                  isAnswerState && correct && styles.correctOptionCard,
                  isAnswerState && !correct && styles.wrongOptionCard,
                ]}
                activeOpacity={disabled ? 1 : 0.8}
                onPress={() => handleSelect(opt.value)}
              >
                <View
                  style={[
                    styles.indicatorCircle,
                    selected && styles.selectedIndicatorCircle,
                    isAnswerState && correct && styles.correctIndicatorCircle,
                    isAnswerState && !correct && styles.wrongIndicatorCircle,
                  ]}
                >
                  <Text
                    style={[
                      styles.indicatorText,
                      (selected || isAnswerState) && styles.selectedIndicatorText,
                    ]}
                  >
                    {opt.label}
                  </Text>
                </View>
                <View style={styles.optionTextContainer}>
                  {opt.text ? (
                    <MathRenderer content={opt.text} textColor={selected ? '#615EFE' : '#333333'} />
                  ) : (
                    <Text style={[styles.optionFallbackText, selected && styles.selectedOptionFallbackText]}>
                      选项 {opt.label}
                    </Text>
                  )}
                </View>
                {isAnswerState && (
                  <View style={styles.statusIconWrapper}>
                    <Text style={correct ? styles.correctIconText : styles.wrongIconText}>
                      {correct ? '✓' : '✕'}
                    </Text>
                  </View>
                )}
              </TouchableOpacity>
            );
          })}
        </View>
      ) : (
        <View style={styles.fieldMissingWarning}>
          <Text style={styles.fieldMissingWarningText}>【警告：选择题未配置选项内容 (options)】</Text>
        </View>
      )}

      <QuestionAnalysis question={question} show={showAnalysis} />
    </BaseQuestion>
  );
}

const styles = StyleSheet.create({
  optionsContainer: {
    width: '100%',
    gap: 12,
  },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 8,
    gap: 12,
  },
  selectedOptionCard: {
    backgroundColor: '#F0F0FF',
    borderColor: '#615EFE',
  },
  correctOptionCard: {
    backgroundColor: '#F0FFF4',
    borderColor: '#22C55E',
  },
  wrongOptionCard: {
    backgroundColor: '#FEF2F2',
    borderColor: '#EF4444',
  },
  indicatorCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDDDDD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedIndicatorCircle: {
    backgroundColor: '#615EFE',
    borderColor: '#615EFE',
  },
  correctIndicatorCircle: {
    backgroundColor: '#22C55E',
    borderColor: '#22C55E',
  },
  wrongIndicatorCircle: {
    backgroundColor: '#EF4444',
    borderColor: '#EF4444',
  },
  indicatorText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
  },
  selectedIndicatorText: {
    color: '#FFFFFF',
  },
  optionTextContainer: {
    flex: 1,
  },
  optionFallbackText: {
    fontSize: 15,
    color: '#333333',
    fontWeight: '400',
  },
  selectedOptionFallbackText: {
    color: '#615EFE',
    fontWeight: '600',
  },
  statusIconWrapper: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  correctIconText: {
    color: '#22C55E',
    fontSize: 16,
    fontWeight: '700',
  },
  wrongIconText: {
    color: '#EF4444',
    fontSize: 16,
    fontWeight: '700',
  },
  fieldMissingWarning: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    borderStyle: 'dashed',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    marginVertical: 6,
    alignSelf: 'flex-start',
  },
  fieldMissingWarningText: {
    color: '#EF4444',
    fontSize: 13,
  },
});

// imates-web/src/components/exercise/ChoiceQuestion.vue
<template>
  <BaseQuestion :question="question" :show-title="showTitle" :show-id="showId" :show-analysis="false">
    <template #extra>
      <slot name="extra"></slot>
    </template>
    <div class="choice-options" v-if="processedOptions && processedOptions.length > 0">
      <div 
        v-for="opt in processedOptions" 
        :key="opt.value"
        class="option-item"
        :class="{ 
          selected: isSelected(opt.value),
          correct: isSelected(opt.value) && isCorrect(opt.value) && disabled,
          wrong: isSelected(opt.value) && !isCorrect(opt.value) && disabled
        }"
        @click="handleSelect(opt.value)"
      >
        <div class="option-label">{{ opt.label }}</div>
        <div class="option-text" v-html="renderMessageContent(opt.text)"></div>
        <div class="option-status-icon" v-if="disabled && isSelected(opt.value)">
          <q-icon v-if="isCorrect(opt.value)" name="check_circle" color="green" size="20px" />
          <q-icon v-else name="cancel" color="red" size="20px" />
        </div>
      </div>
    </div>
    <div v-else class="field-missing-warning" style="margin-bottom: 12px;">【警告：选择题未配置选项内容 (options)】</div>
    
    <QuestionAnalysis :question="question" :show="showAnalysis" />
  </BaseQuestion>
</template>

<script lang="ts">
export default {
  name: 'ChoiceQuestion'
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import type { ExerciseItem } from '../../types'
import { useMessageRenderer } from '../../composables/useMessageRenderer'
import BaseQuestion from './BaseQuestion.vue'
import QuestionAnalysis from './QuestionAnalysis.vue'

const props = withDefaults(defineProps<{
  question: ExerciseItem
  modelValue?: string[]
  showTitle?: boolean
  showId?: boolean
  showAnalysis?: boolean
  disabled?: boolean
}>(), {
  showTitle: false,
  showId: true,
  showAnalysis: false,
  disabled: false
})

const emit = defineEmits(['update:modelValue', 'change'])

const { renderMessageContent } = useMessageRenderer()

const processedOptions = computed(() => {
  const rawOptions = props.question.structuredContent?.options || []
  return rawOptions.map((opt) => ({
    // 新结构：使用 id 作为标识和显示卷标，content 作为内容
    value: opt.id || '',
    label: opt.id || '',
    text: opt.content || ''
  }))
})

const isSelected = (value: string) => props.modelValue?.includes(value)
const isCorrect = (value: string) => {
  const answer = props.question.structuredContent?.answer
  if (Array.isArray(answer)) {
    return answer.includes(value)
  }
  // 仅保留对字符串化的支持，不再处理旧版的布尔值回退（已在数据层统一）
  return String(answer) === value
}

const handleSelect = (value: string) => {
  if (props.disabled) return 

  let newValue = [...(props.modelValue || [])]
  const index = newValue.indexOf(value)
  if (index > -1) {
    newValue.splice(index, 1)
  } else {
    const isMultiple = props.question.structuredContent?.type === 'multiple_choice'

    if (isMultiple) {
      newValue.push(value)
      newValue.sort()
    } else {
      newValue = [value]
    }
  }
  emit('update:modelValue', newValue)
  emit('change', newValue)
}
</script>

<style scoped>
.choice-options {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.option-item {
  display: flex;
  align-items: center;
  padding: 12px 16px;
  border: 1px solid #eee;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
  gap: 12px;
  position: relative;
}

.option-item:hover:not(.selected) {
  background: #f9f9ff;
  border-color: #615efe;
}

.option-item.selected {
  background: #f0f0ff;
  border-color: #615efe;
}

.option-label {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  border: 1px solid #ddd;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  color: #666;
  flex-shrink: 0;
}

.option-item.selected .option-label {
  background: #615efe;
  color: white;
  border-color: #615efe;
}

.option-text {
  flex: 1;
  font-size: 15px;
}

.option-status-icon {
  width: 20px;
  height: 20px;
}

.option-item.correct {
  border-color: #22c55e;
  background: #f0fff4;
}

.option-item.correct .option-label {
  background: #22c55e;
  border-color: #22c55e;
  color: white;
}

.option-item.wrong {
  border-color: #ef4444;
  background: #fef2f2;
}

.option-item.wrong .option-label {
  background: #ef4444;
  border-color: #ef4444;
  color: white;
}

.field-missing-warning {
  color: #ef4444;
  background-color: #fef2f2;
  border: 1px dashed #fca5a5;
  padding: 8px 12px;
  border-radius: 6px;
  font-size: 13px;
  margin-top: 4px;
  display: block;
  width: fit-content;
}

:deep(table) {
  border-collapse: collapse;
  width: 100%;
  margin: 12px 0;
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid #e2e8f0;
}
:deep(th), :deep(td) {
  border: 1px solid #e2e8f0;
  padding: 8px 12px;
  text-align: left;
}
:deep(th) {
  background-color: #f8fafc;
  font-weight: 600;
  color: #475569;
}
</style>
