// imates-react/src/components/messages/ImageMessage.tsx
import React, { useState, useEffect } from 'react'
import '@/components/messages/ImageMessage.css'

interface ImageMessageProps {
  base64DataUrl?: string
  url?: string
  filePath?: string
  width?: number
  height?: number
  fileSize?: number
  isUser?: boolean
  showInfo?: boolean
  maxWidth?: number
  maxHeight?: number
}

export const ImageMessage: React.FC<ImageMessageProps> = ({
  base64DataUrl,
  url,
  filePath,
  width = 0,
  height = 0,
  fileSize = 0,
  isUser = false,
  showInfo = false,
  maxWidth = 200,
  maxHeight = 200,
}) => {
  const [isPreviewOpen, setIsPreviewOpen] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  const [hasError, setHasError] = useState(false)

  const imgSrc = base64DataUrl || url || filePath

  const formatFileSize = (bytes: number): string => {
    if (bytes === 0) return '0 B'
    const k = 1024
    const sizes = ['B', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i]
  }

  const handleClick = () => {
    if (!isLoading && !hasError) {
      setIsPreviewOpen(true)
    }
  }

  const handleClose = () => {
    setIsPreviewOpen(false)
  }

  const retryLoad = (e: React.MouseEvent) => {
    e.stopPropagation()
    setIsLoading(true)
    setHasError(false)
    // 强制重新加载图片
    const img = new Image()
    img.onload = () => {
      setIsLoading(false)
      setHasError(false)
    }
    img.onerror = () => {
      setIsLoading(false)
      setHasError(true)
    }
    img.src = imgSrc + (imgSrc?.includes('?') ? '&' : '?') + 't=' + Date.now()
  }

  const getImageStyle = (): React.CSSProperties => {
    if (!width || !height) {
      return {
        maxWidth: `${maxWidth}px`,
        maxHeight: `${maxHeight}px`,
      }
    }

    // 计算缩放比例，保持宽高比
    const widthRatio = maxWidth / width
    const heightRatio = maxHeight / height
    const scale = Math.min(widthRatio, heightRatio, 1)

    return {
      width: `${width * scale}px`,
      height: `${height * scale}px`,
    }
  }

  useEffect(() => {
    if (imgSrc) {
      const img = new Image()
      img.onload = () => {
        setIsLoading(false)
        setHasError(false)
      }
      img.onerror = () => {
        setIsLoading(false)
        setHasError(true)
      }
      img.src = imgSrc
    }
  }, [imgSrc])

  if (hasError) {
    return (
      <div className={`image-message error ${isUser ? 'user' : 'ai'}`}>
        <svg viewBox="0 0 24 24" width="32" height="32" fill="#999">
          <path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z"/>
        </svg>
        <span className="error-text">图片加载失败</span>
        <button className="retry-btn" onClick={retryLoad}>重试</button>
      </div>
    )
  }

  return (
    <>
      <div 
        className={`image-message ${isUser ? 'user' : 'ai'}`}
        onClick={handleClick}
      >
        <div className="image-container">
          {isLoading && (
            <div className="image-loading">
              <div className="image-loading-dots">
                <span></span>
                <span></span>
                <span></span>
              </div>
              <span className="loading-text">加载中...</span>
            </div>
          )}
          <img
            src={imgSrc}
            alt={`图片消息 ${width}×${height}`}
            style={{ ...getImageStyle(), display: isLoading ? 'none' : 'block' }}
          />
          {showInfo && !isLoading && !hasError && (
            <div className="image-info">
              <div className="image-size">{formatFileSize(fileSize)}</div>
              <div className="image-dimensions">{width} × {height}</div>
            </div>
          )}
        </div>
      </div>

      {isPreviewOpen && (
        <div className="image-preview-overlay" onClick={handleClose}>
          <div className="image-preview-content">
            <img src={imgSrc} alt="预览" />
          </div>
          <button className="image-preview-close" onClick={handleClose}>
            <svg viewBox="0 0 24 24" width="24" height="24" fill="white">
              <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
            </svg>
          </button>
        </div>
      )}
    </>
  )
}

export default ImageMessage

// imates-web/src/components/chat/ImageMessage.vue
<template>
  <div class="image-message" :class="{ 'image-message-user': isUser }">
    <div class="image-container" @click="handleImageClick">
      <!-- 图片加载状态 -->
      <div v-if="isLoading" class="image-loading">
        <q-spinner-dots color="primary" size="24px" />
        <span class="loading-text">加载中...</span>
      </div>
      <!-- 图片内容 -->
      <img
        v-else-if="!loadError"
        :src="imageUrl"
        :alt="altText"
        class="message-image"
        @load="handleImageLoad"
        @error="handleImageError"
        :style="imageStyle"
      />
      
      <!-- 加载失败状态 -->
      <div v-else class="image-error">
        <q-icon name="broken_image" size="32px" color="grey-5" />
        <span class="error-text">图片加载失败</span>
        <q-btn
          flat
          size="sm"
          color="primary"
          label="重试"
          @click="retryLoad"
        />
      </div>
      
      <!-- 图片信息覆盖层 -->
      <div v-if="showInfo && !isLoading && !loadError" class="image-info">
        <div class="image-size">{{ formatFileSize(fileSize) }}</div>
        <div class="image-dimensions">{{ width }} × {{ height }}</div>
      </div>
    </div>
    
    <!-- 图片预览对话框 -->
    <ImageViewer
      v-model="showPreview" 
      :image-url="imageUrl"
            :alt="altText"
          />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import ImageViewer from '../ImageViewer.vue'

// 导入类型定义
import type { ImageMessageProps } from '../../types'

// 定义Props（直接使用类型，避免空接口）
type Props = ImageMessageProps

const props = withDefaults(defineProps<Props>(), {
  width: 0,
  height: 0,
  fileSize: 0,
  isUser: false,
  maxWidth: 200,
  maxHeight: 200,
  showInfo: false
})

const isLoading = ref(true)
const loadError = ref(false)
const showPreview = ref(false)

const imageUrl = computed(() => {
  // 只使用 base64DataUrl
  return props.base64DataUrl
})

const altText = computed(() => {
  return `图片消息 ${props.width}×${props.height}`
})

const imageStyle = computed(() => {
  if (!props.width || !props.height) {
    return {
      maxWidth: `${props.maxWidth}px`,
      maxHeight: `${props.maxHeight}px`
    }
  }
  
  // 计算缩放比例，保持宽高比
  const widthRatio = props.maxWidth / props.width
  const heightRatio = props.maxHeight / props.height
  const scale = Math.min(widthRatio, heightRatio, 1)
  
  return {
    width: `${props.width * scale}px`,
    height: `${props.height * scale}px`
  }
})

const handleImageLoad = () => {
  isLoading.value = false
  loadError.value = false
}

const handleImageError = () => {
  isLoading.value = false
  loadError.value = true
}

const handleImageClick = () => {
  if (!isLoading.value && !loadError.value) {
    showPreview.value = true
  }
}

const retryLoad = () => {
  isLoading.value = true
  loadError.value = false
  // 强制重新加载图片
  const img = new Image()
  img.onload = handleImageLoad
  img.onerror = handleImageError
  img.src = imageUrl.value + '?t=' + Date.now()
}


const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 B'
  
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i]
}

onMounted(() => {
  // 预加载图片
  const img = new Image()
  img.onload = handleImageLoad
  img.onerror = handleImageError
  img.src = imageUrl.value
})
</script>

<style scoped>
.image-message {
  min-width: 120px;
  max-width: 220px;
  cursor: pointer;
  user-select: none;
}

.image-container {
  position: relative;
  border-radius: 12px;
  overflow: hidden;
  background: #f5f5f5;
  transition: all 0.2s ease;
}

.image-container:hover {
  transform: scale(1.02);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.message-image {
  width: 100%;
  height: auto;
  display: block;
  border-radius: 12px;
}

.image-loading,
.image-error {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;
  min-height: 120px;
  color: #666;
}

.loading-text,
.error-text {
  margin-top: 8px;
  font-size: 14px;
}

.image-info {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background: linear-gradient(transparent, rgba(0, 0, 0, 0.7));
  color: white;
  padding: 8px 12px;
  font-size: 12px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  opacity: 0;
  transition: opacity 0.2s ease;
}

.image-container:hover .image-info {
  opacity: 1;
}

.image-message-user .image-container {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
}


/* 深色模式支持 */
@media (prefers-color-scheme: dark) {
  .image-container {
    background: #3a3a3a;
  }
  
  .image-loading,
  .image-error {
    color: #ccc;
  }
  
  .preview-header {
    border-bottom-color: #4a4a4a;
  }
}
</style>
