// imates-react/src/components/chat/Input/VoiceRecorder.tsx
import React, { useState, useEffect, useRef } from 'react'
import './VoiceRecorder.css'

export interface VoiceRecorderProps {
  isRecording?: boolean
  showCancelHint?: boolean
}

export const VoiceRecorder: React.FC<VoiceRecorderProps> = ({ 
  isRecording = false, 
  showCancelHint = false 
}) => {
  const [recordingTime, setRecordingTime] = useState(0)
  const timerRef = useRef<number | null>(null)

  const formatTime = (seconds: number): string => {
    const mins = Math.floor(seconds / 60)
    const secs = seconds % 60
    return `${mins}:${secs.toString().padStart(2, '0')}`
  }

  useEffect(() => {
    if (isRecording) {
      setRecordingTime(0)
      if (timerRef.current) {
        clearInterval(timerRef.current)
      }
      timerRef.current = window.setInterval(() => {
        setRecordingTime(prev => prev + 1)
      }, 1000)
    } else {
      if (timerRef.current) {
        clearInterval(timerRef.current)
        timerRef.current = null
      }
      setRecordingTime(0)
    }

    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current)
      }
    }
  }, [isRecording])

  return (
    <div className={`voice-recorder ${isRecording ? 'recording' : ''}`}>
      {isRecording && !showCancelHint && (
        <div className="recording-status">
          <div className="recording-animation">
            <div className="pulse-circle"></div>
            <svg viewBox="0 0 24 24" width="32" height="32" fill="white">
              <path d="M12 14c1.66 0 3-1.34 3-3V5c0-1.66-1.34-3-3-3S9 3.34 9 5v6c0 1.66 1.34 3 3 3zm5.91-3c-.49 0-.9.36-.98.85C16.52 14.2 14.47 16 12 16s-4.52-1.8-4.93-4.15c-.08-.49-.49-.85-.98-.85-.61 0-1.09.54-1 1.14.49 3 2.89 5.35 5.91 5.78V20c0 .55.45 1 1 1s1-.45 1-1v-2.08c3.02-.43 5.42-2.78 5.91-5.78.1-.6-.39-1.14-1-1.14z"/>
            </svg>
          </div>
          <div className="recording-info">
            <div className="recording-text">正在录音...</div>
            <div className="recording-time">{formatTime(recordingTime)}</div>
          </div>
          <div className="recording-hint">
            <div className="hint-text">松开发送，上滑取消</div>
            <svg viewBox="0 0 24 24" width="18" height="18" fill="#999">
              <path d="M7.41 15.41L12 10.83l4.59 4.58L18 14l-6-6-6 6z"/>
            </svg>
          </div>
        </div>
      )}
      
      {showCancelHint && (
        <div className="cancel-hint">
          <img src="/icons/delete.svg" alt="取消录音" width="32" height="32" />
          <div className="cancel-text">松开取消发送</div>
        </div>
      )}
    </div>
  )
}

export default VoiceRecorder

// imates-web/src/components/chat/VoiceRecorder.vue
<template>
  <div class="voice-recorder" :class="{ 'recording': isRecording }">
    <!-- 录音状态显示 -->
    <div v-if="isRecording" class="recording-status">
      <div class="recording-animation">
        <div class="pulse-circle"></div>
        <q-icon name="mic" size="24px" color="white" />
      </div>
      <div class="recording-info">
        <div class="recording-text">正在录音...</div>
        <div class="recording-time">{{ formatTime(recordingTime) }}</div>
      </div>
      <div class="recording-hint">
        <div class="hint-text">松开发送，上滑取消</div>
        <q-icon name="keyboard_arrow_up" size="16px" />
      </div>
    </div>
    
    <!-- 取消录音提示 -->
    <div v-if="props.showCancelHint" class="cancel-hint">
      <q-icon name="delete" size="24px" color="red" />
      <div class="cancel-text">松开取消发送</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onUnmounted } from 'vue'

// 导入类型定义
import type { VoiceRecorderProps } from '../../types'

// 定义Props
interface Props extends VoiceRecorderProps {}

const props = withDefaults(defineProps<Props>(), {
  showCancelHint: false
})

const recordingTime = ref(0)
let recordingTimer: number | null = null

const formatTime = (seconds: number): string => {
  const mins = Math.floor(seconds / 60)
  const secs = seconds % 60
  return `${mins}:${secs.toString().padStart(2, '0')}`
}

const startTimer = () => {
  recordingTime.value = 0
  if (recordingTimer) {
    clearInterval(recordingTimer)
  }
  recordingTimer = window.setInterval(() => {
    recordingTime.value++
  }, 1000)
}

const stopTimer = () => {
  if (recordingTimer) {
    clearInterval(recordingTimer)
    recordingTimer = null
  }
  recordingTime.value = 0
}

// 监听录音状态变化
watch(() => props.isRecording, (newValue, oldValue) => {
  if (newValue) {
    startTimer()
  } else {
    stopTimer()
  }
}, { immediate: true })

onUnmounted(() => {
  stopTimer()
})
</script>

<style scoped>
.voice-recorder {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.8);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
  opacity: 0;
  visibility: hidden;
  transition: all 0.3s ease;
}

.voice-recorder.recording {
  opacity: 1;
  visibility: visible;
}

.recording-status {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 20px;
  color: white;
  text-align: center;
}

.recording-animation {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 80px;
  height: 80px;
  background: #ff4444;
  border-radius: 50%;
  box-shadow: 0 4px 20px rgba(255, 68, 68, 0.4);
}

.pulse-circle {
  position: absolute;
  width: 100%;
  height: 100%;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-radius: 50%;
  animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
  0% {
    transform: scale(1);
    opacity: 1;
  }
  100% {
    transform: scale(1.5);
    opacity: 0;
  }
}

.recording-info {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.recording-text {
  font-size: 18px;
  font-weight: 500;
}

.recording-time {
  font-size: 24px;
  font-weight: bold;
  color: #ff4444;
}

.recording-hint {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  opacity: 0.8;
}

.hint-text {
  font-size: 14px;
}

.cancel-hint {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  color: #ff4444;
  text-align: center;
}

.cancel-text {
  font-size: 16px;
  font-weight: 500;
}

/* 动画效果 */
.voice-recorder.recording .recording-animation {
  animation: recording-bounce 0.3s ease-out;
}

@keyframes recording-bounce {
  0% {
    transform: scale(0.8);
  }
  50% {
    transform: scale(1.1);
  }
  100% {
    transform: scale(1);
  }
}
</style>
