// imates-react/src/views/LearningContentView.tsx
import React, { useMemo } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import './LearningContentView.css'

export const LearningContentView: React.FC = () => {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()

  const fileName = searchParams.get('fileName') || ''
  const fileExtension = useMemo(() => {
    const ext = fileName.split('.').pop()?.toLowerCase() || ''
    return ext
  }, [fileName])

  const viewerType = useMemo(() => {
    const ext = fileExtension
    switch (ext) {
      case 'pdf':
        return 'pdf'
      case 'html':
      case 'htm':
        return 'html'
      case 'mp4':
      case 'avi':
      case 'mov':
      case 'wmv':
      case 'flv':
      case 'webm':
        return 'video'
      default:
        return 'unsupported'
    }
  }, [fileExtension])

  const handleGoBack = () => {
    const fromLearning = searchParams.get('fromLearning')
    if (fromLearning === 'true') {
      navigate({
        pathname: '/learning',
        search: `?nodeId=${searchParams.get('learningNodeId') || ''}&sectionName=${searchParams.get('textbookName') || ''}&id=${searchParams.get('id') || ''}&level=${searchParams.get('learningLevel') || ''}`,
      })
    } else {
      navigate(-1)
    }
  }

  const renderViewer = () => {
    switch (viewerType) {
      case 'pdf':
        return <div className="viewer-placeholder">PDF 查看器</div>
      case 'html':
        return <div className="viewer-placeholder">HTML 查看器</div>
      case 'video':
        return <div className="viewer-placeholder">视频播放器</div>
      default:
        return (
          <div className="unsupported-viewer">
            <div className="unsupported-content">
              <svg viewBox="0 0 24 24" width="80" height="80" fill="#999">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
              </svg>
              <div className="unsupported-title">不支持的文件类型</div>
              <div className="unsupported-desc">
                当前文件类型（{fileExtension}）暂不支持预览
              </div>
              <div className="unsupported-filename">
                文件名：{fileName}
              </div>
              <button className="back-btn" onClick={handleGoBack}>
                返回
              </button>
            </div>
          </div>
        )
    }
  }

  return (
    <div className="learning-content-view">
      {renderViewer()}
    </div>
  )
}

export default LearningContentView

// imates-MiniApp/src/views/LearningContentView.vue
<template>
  <view class="learning-content-view">
    <!-- 根据文件类型动态加载不同的查看器 -->
    <PdfViewerView v-if="viewerType === 'pdf'" />
    <HtmlViewerView v-else-if="viewerType === 'html'" />
    <VideoViewerView v-else-if="viewerType === 'video'" />
    
    <!-- 不支持的文件类型 -->
    <view v-else class="unsupported-viewer">
      <view class="unsupported-content">
        <image src="/static/icons/folder_open.svg" mode="aspectFit" class="error-icon" />
        <text class="error-title">不支持的文件类型</text>
        <text class="error-desc">当前文件类型（{{ fileExtension }}）暂不支持预览</text>
        <text class="file-name">文件名：{{ fileName }}</text>
        <Button
          variant="primary"
          label="返回"
          @click="handleGoBack"
          class="back-btn"
        />
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import PdfViewerView from './PdfViewerView.vue'
import HtmlViewerView from './HtmlViewerView.vue'
import VideoViewerView from './VideoViewerView.vue'
import Button from '../components/base/Button.vue'

defineOptions({
  name: 'LearningContentView'
})

const route = useRoute()

const fileName = computed(() => (route.query.fileName as string) || '')
const fileExtension = computed(() => {
  const ext = fileName.value.split('.').pop()?.toLowerCase() || ''
  return ext
})

const viewerType = computed(() => {
  const ext = fileExtension.value
  
  switch (ext) {
    case 'pdf':
      return 'pdf'
    case 'html':
    case 'htm':
      return 'html'
    case 'mp4':
    case 'avi':
    case 'mov':
    case 'wmv':
    case 'flv':
    case 'webm':
      return 'video'
    default:
      return 'unsupported'
  }
})

const handleGoBack = () => {
  uni.navigateBack()
}

onMounted(() => {
  console.log('LearningContentView mounted', {
    fileName: fileName.value,
    viewerType: viewerType.value,
    query: route.query,
  })
})
</script>

<style scoped>
.learning-content-view {
  width: 100%;
  height: 100vh;
  overflow: hidden;
}

.unsupported-viewer {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #fafafa;
}

.unsupported-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 80rpx 40rpx;
  background-color: #ffffff;
  border-radius: 16rpx;
  box-shadow: 0 4rpx 16rpx rgba(0, 0, 0, 0.05);
  width: 80%;
}

.error-icon {
  width: 160rpx;
  height: 160rpx;
  margin-bottom: 32rpx;
  opacity: 0.5;
}

.error-title {
  font-size: 36rpx;
  font-weight: 600;
  color: #333;
  margin-bottom: 16rpx;
}

.error-desc {
  font-size: 28rpx;
  color: #999;
  margin-bottom: 32rpx;
}

.file-name {
  font-size: 24rpx;
  color: #666;
  margin-bottom: 48rpx;
  text-align: center;
}

.back-btn {
  width: 240rpx;
}
</style>
