// imates-react/src/components/display/ImageViewer.tsx
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react'
import ReactDOM from 'react-dom'
import downloadIcon from '/icons/download.svg'
import { androidBridge } from '@/services/business/android-bridge'
import { showMessage } from '@/utils'
import '@/components/display/ImageViewer.css'

interface ImageItem {
  url: string
  alt?: string
}

interface ImageViewerProps {
  open: boolean
  onClose: () => void
  imageUrl?: string
  alt?: string
  images?: ImageItem[]
  initialIndex?: number
  onChange?: (index: number) => void
}

type Point = { x: number; y: number }

export const ImageViewer: React.FC<ImageViewerProps> = ({
  open,
  onClose,
  imageUrl = '',
  alt = '图片预览',
  images = [],
  initialIndex = 0,
  onChange,
}) => {
  const [currentIndex, setCurrentIndex] = useState(initialIndex)
  const [translateX, setTranslateX] = useState(0)
  const [translateY, setTranslateY] = useState(0)
  const [scale, setScale] = useState(1)
  const [rotationDeg, setRotationDeg] = useState(0)
  const [enableTransition, setEnableTransition] = useState(false)

  const previewContentRef = useRef<HTMLDivElement>(null)
  const activePointers = useRef(new Map<number, Point>())
  const lastSinglePointer = useRef<{ id: number; x: number; y: number } | null>(null)
  const gestureStart = useRef<{
    distance: number
    angleDeg: number
    midpoint: Point
    startScale: number
    startRotationDeg: number
    startTranslateX: number
    startTranslateY: number
  } | null>(null)

  const MIN_SCALE = 0.5
  const MAX_SCALE = 5
  const ROTATION_THRESHOLD = 7

  useEffect(() => {
    if (open) {
      setCurrentIndex(initialIndex)
      resetTransform()
    }
  }, [open, initialIndex])

  const resetTransform = useCallback(() => {
    setTranslateX(0)
    setTranslateY(0)
    setScale(1)
    setRotationDeg(0)
    setEnableTransition(false)
    activePointers.current.clear()
    gestureStart.current = null
  }, [])

  useEffect(() => {
    resetTransform()
  }, [currentIndex, imageUrl, resetTransform])

  const snapToNearest90 = (deg: number, startDeg: number) => {
    const deltaDeg = deg - startDeg
    const absoluteDelta = Math.abs(deltaDeg)
    if (absoluteDelta <= 30) {
      return startDeg
    } else {
      return Math.round(deg / 90) * 90
    }
  }

  const imageStyle = useMemo(() => {
    const transition = enableTransition ? 'transform 0.3s ease' : 'none'
    return {
      transform: `translate3d(${translateX}px, ${translateY}px, 0) scale(${scale}) rotate(${rotationDeg}deg)`,
      transformOrigin: 'center center',
      transition,
    }
  }, [translateX, translateY, scale, rotationDeg, enableTransition])

  const clamp = (v: number, min: number, max: number) => Math.min(max, Math.max(min, v))
  const getDistance = (a: Point, b: Point) => Math.hypot(a.x - b.x, a.y - b.y)
  const getAngleDeg = (a: Point, b: Point) => (Math.atan2(b.y - a.y, b.x - a.x) * 180) / Math.PI
  const getMidpoint = (a: Point, b: Point): Point => ({ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 })

  const handlePointerDown = (e: React.PointerEvent) => {
    if (!open) return
    e.preventDefault()
    e.stopPropagation()
    setEnableTransition(false)
    activePointers.current.set(e.pointerId, { x: e.clientX, y: e.clientY })

    try {
      (e.target as HTMLElement).setPointerCapture(e.pointerId)
    } catch (err) {}

    if (activePointers.current.size === 1) {
      lastSinglePointer.current = { id: e.pointerId, x: e.clientX, y: e.clientY }
      gestureStart.current = null
    } else if (activePointers.current.size === 2) {
      const pts = Array.from(activePointers.current.values())
      const a = pts[0]
      const b = pts[1]
      gestureStart.current = {
        distance: getDistance(a, b),
        angleDeg: getAngleDeg(a, b),
        midpoint: getMidpoint(a, b),
        startScale: scale,
        startRotationDeg: rotationDeg,
        startTranslateX: translateX,
        startTranslateY: translateY,
      }
      lastSinglePointer.current = null
    }
  }

  const handlePointerMove = (e: React.PointerEvent) => {
    if (!open || !activePointers.current.has(e.pointerId)) return
    e.preventDefault()
    e.stopPropagation()
    activePointers.current.set(e.pointerId, { x: e.clientX, y: e.clientY })

    if (activePointers.current.size === 1 && lastSinglePointer.current?.id === e.pointerId) {
      const dx = e.clientX - lastSinglePointer.current.x
      const dy = e.clientY - lastSinglePointer.current.y
      setTranslateX(prev => prev + dx)
      setTranslateY(prev => prev + dy)
      lastSinglePointer.current = { id: e.pointerId, x: e.clientX, y: e.clientY }
    } else if (activePointers.current.size >= 2 && gestureStart.current) {
      const pts = Array.from(activePointers.current.values())
      const a = pts[0]
      const b = pts[1]
      const distance = getDistance(a, b)
      const angleDeg = getAngleDeg(a, b)
      const midpoint = getMidpoint(a, b)

      const scaleFactor = gestureStart.current.distance > 0 ? distance / gestureStart.current.distance : 1
      const newScale = clamp(gestureStart.current.startScale * scaleFactor, MIN_SCALE, MAX_SCALE)
      const deltaAngle = angleDeg - gestureStart.current.angleDeg

      let newRotation = rotationDeg
      if (Math.abs(deltaAngle) > ROTATION_THRESHOLD) {
        newRotation = gestureStart.current.startRotationDeg + deltaAngle
      }

      const containerRect = previewContentRef.current?.getBoundingClientRect()
      if (containerRect) {
        const centerX = containerRect.left + containerRect.width / 2
        const centerY = containerRect.top + containerRect.height / 2
        const scaleRatio = newScale / gestureStart.current.startScale
        const startRelativeX = gestureStart.current.midpoint.x - centerX - gestureStart.current.startTranslateX
        const startRelativeY = gestureStart.current.midpoint.y - centerY - gestureStart.current.startTranslateY

        setTranslateX(midpoint.x - centerX - startRelativeX * scaleRatio)
        setTranslateY(midpoint.y - centerY - startRelativeY * scaleRatio)
        setScale(newScale)
        setRotationDeg(newRotation)
      }
    }
  }

  const handlePointerUp = (e: React.PointerEvent) => {
    if (!activePointers.current.has(e.pointerId)) return
    e.preventDefault()
    e.stopPropagation()
    activePointers.current.delete(e.pointerId)

    try {
      (e.target as HTMLElement).releasePointerCapture(e.pointerId)
    } catch (err) {}

    if (activePointers.current.size === 1) {
      const remainingId = Array.from(activePointers.current.keys())[0]
      const pt = activePointers.current.get(remainingId)
      if (pt) {
        lastSinglePointer.current = { id: remainingId, x: pt.x, y: pt.y }
      }
      gestureStart.current = null
    } else if (activePointers.current.size < 1) {
      const startRotationDeg = gestureStart.current?.startRotationDeg || 0
      lastSinglePointer.current = null
      gestureStart.current = null

      const snappedRotation = snapToNearest90(rotationDeg, startRotationDeg)
      if (snappedRotation !== rotationDeg) {
        setEnableTransition(true)
        setRotationDeg(snappedRotation)
        setTimeout(() => setEnableTransition(false), 300)
      }
    }
  }

  const currentImageUrl = images.length > 0 ? images[currentIndex]?.url : imageUrl
  const currentAlt = images.length > 0 ? images[currentIndex]?.alt || alt : alt
  const totalImages = images.length > 0 ? images.length : 1
  const showPrev = images.length > 1 && currentIndex > 0
  const showNext = images.length > 1 && currentIndex < images.length - 1

  const handlePrev = () => {
    if (currentIndex > 0) {
      const next = currentIndex - 1
      setCurrentIndex(next)
      onChange?.(next)
    }
  }

  const handleNext = () => {
    if (currentIndex < images.length - 1) {
      const next = currentIndex + 1
      setCurrentIndex(next)
      onChange?.(next)
    }
  }

  const handleClose = () => {
    onClose()
    resetTransform()
  }

  const handleSave = async () => {
    if (!currentImageUrl) return
    try {
      if (androidBridge.isAndroidBridgeAvailable() && androidBridge.saveBase64ImageToGallery) {
        let dataUrl = currentImageUrl
        if (!dataUrl.startsWith('data:image/')) {
          const resp = await fetch(currentImageUrl)
          const blob = await resp.blob()
          dataUrl = await new Promise((resolve) => {
            const reader = new FileReader()
            reader.onload = () => resolve(String(reader.result))
            reader.readAsDataURL(blob)
          })
        }
        const ext = dataUrl.match(/data:image\/([^;]+);/)?.[1] || 'png'
        const filename = `image_${Date.now()}.${ext}`
        const result = androidBridge.saveBase64ImageToGallery(dataUrl, filename)
        if (result?.success) {
          showMessage('已保存到相册', 'success')
          return
        }
      }

      if (currentImageUrl.startsWith('data:image/')) {
        const link = document.createElement('a')
        link.href = currentImageUrl
        link.download = `image_${Date.now()}.png`
        link.click()
        showMessage('开始下载', 'success')
      } else {
        const resp = await fetch(currentImageUrl)
        const blob = await resp.blob()
        const url = URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.href = url
        link.download = `image_${Date.now()}.png`
        link.click()
        URL.revokeObjectURL(url)
        showMessage('开始下载', 'success')
      }
    } catch (err) {
      window.open(currentImageUrl, '_blank', 'noopener')
      showMessage('已在新窗口打开，请长按/右键保存', 'info')
    }
  }

  useEffect(() => {
    const handleKeydown = (e: KeyboardEvent) => {
      if (!open) return
      if (e.key === 'ArrowLeft') handlePrev()
      else if (e.key === 'ArrowRight') handleNext()
      else if (e.key === 'Escape') handleClose()
    }
    window.addEventListener('keydown', handleKeydown)
    return () => window.removeEventListener('keydown', handleKeydown)
  }, [open, currentIndex, images.length])

  if (!open) return null

  return ReactDOM.createPortal(
    <div className="image-viewer-root">
      <div className="preview-overlay" onClick={handleClose}>
        <button type="button" className="close-btn" onClick={(e) => { e.stopPropagation(); handleClose(); }}>✕</button>
        <button type="button" className="save-btn" onClick={(e) => { e.stopPropagation(); handleSave(); }} title="保存到本地">
          <img src={downloadIcon} alt="下载" className="save-icon" />
        </button>

        {showPrev && <button type="button" className="nav-btn prev-btn" onClick={(e) => { e.stopPropagation(); handlePrev(); }} title="上一张">‹</button>}
        {showNext && <button type="button" className="nav-btn next-btn" onClick={(e) => { e.stopPropagation(); handleNext(); }} title="下一张">›</button>}

        {totalImages > 1 && <div className="image-counter">{currentIndex + 1} / {totalImages}</div>}

        <div
          ref={previewContentRef}
          className="preview-content"
          onClick={(e) => e.stopPropagation()}
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerCancel={handlePointerUp}
          onPointerLeave={handlePointerUp}
        >
          {currentImageUrl && (
            <img
              src={currentImageUrl}
              alt={currentAlt}
              className="preview-image"
              style={imageStyle}
            />
          )}
        </div>
      </div>
    </div>,
    document.body
  )
}

export default ImageViewer

// imates-MiniApp/src/components/display/ImageViewer.vue
<template>
  <!-- 在小程序中，不使用 Teleport，直接使用 fixed 定位的 view -->
  <view v-if="modelValue" class="image-viewer-root">
    <view class="preview-overlay" @click="handleClose">
      <!-- 关闭按钮 -->
      <button
        class="close-btn"
        @click.stop="handleClose"
      >
        <text>✕</text>
      </button>

      <button
        class="save-btn"
        @click.stop="handleSave"
      >
        <image :src="downloadIcon" mode="aspectFit" class="save-icon" />
      </button>

      <!-- 上一张按钮 -->
      <button
        v-if="showPrev"
        class="nav-btn prev-btn"
        @click.stop="handlePrev"
      >
        <text>‹</text>
      </button>

      <!-- 下一张按钮 -->
      <button
        v-if="showNext"
        class="nav-btn next-btn"
        @click.stop="handleNext"
      >
        <text>›</text>
      </button>

      <!-- 图片计数器 -->
      <view v-if="totalImages > 1" class="image-counter">
        <text>{{ currentIndex + 1 }} / {{ totalImages }}</text>
      </view>

      <!-- 图片预览区域 -->
      <view
        class="preview-content"
        @click.stop
        @touchstart="handleTouchStart"
        @touchmove="handleTouchMove"
        @touchend="handleTouchEnd"
        @touchcancel="handleTouchEnd"
      >
        <image
          v-if="currentImageUrl"
          :src="currentImageUrl"
          mode="aspectFit"
          class="preview-image"
          :style="imageStyle"
        />
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import downloadIcon from '/icons/download.svg'
import { androidBridge } from '@/services/business/android-bridge'
import { showMessage } from '@/utils'
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'

interface ImageItem {
  url: string
  alt?: string
}

interface Props {
  modelValue: boolean
  imageUrl?: string
  alt?: string
  images?: ImageItem[]
  initialIndex?: number
}

const props = withDefaults(defineProps<Props>(), {
  alt: '图片预览',
  images: () => [],
  initialIndex: 0,
  imageUrl: ''
})

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  'change': [index: number]
}>()

const currentIndex = ref(props.initialIndex)

const previewContentRef = ref<HTMLElement | null>(null)

const translateX = ref(0)
const translateY = ref(0)
const scale = ref(1)
const rotationDeg = ref(0)

const enableTransition = ref(false) // 用于控制吸附时的过渡动画

const MIN_SCALE = 0.5
const MAX_SCALE = 5

// 旋转角度阈值：只有角度变化超过此值才进行旋转
const ROTATION_THRESHOLD = 7 // 5度

const resetTransform = () => {
  translateX.value = 0
  translateY.value = 0
  scale.value = 1
  rotationDeg.value = 0

  activeTouches.clear()
  gestureStart.value = null
  enableTransition.value = false
}

const snapToNearest90 = (deg: number, startDeg: number) => {
  // 计算相对于开始角度的偏移（不归一化，保持累积性）
  const deltaDeg = deg - startDeg
  const absoluteDelta = Math.abs(deltaDeg)
  
  // 判断是否超过30度
  if (absoluteDelta <= 30) {
    // 30度以内，回到开始时的角度
    return startDeg
  } else {
    // 超过30度，吸附到最近的90度倍数
    // 找到当前角度最接近的90度倍数
    const nearest90 = Math.round(deg / 90) * 90
    return nearest90
  }
}

const imageStyle = computed(() => {
  const transition = enableTransition.value ? 'transform 0.3s ease' : 'none'
  return {
    transform: `translate3d(${translateX.value}px, ${translateY.value}px, 0) scale(${scale.value}) rotate(${rotationDeg.value}deg)`,
    transformOrigin: 'center center',
    transition
  } as Record<string, string>
})

type Point = { x: number; y: number }

const clamp = (v: number, min: number, max: number) => Math.min(max, Math.max(min, v))

const getDistance = (a: Point, b: Point) => {
  const dx = a.x - b.x
  const dy = a.y - b.y
  return Math.hypot(dx, dy)
}

const getAngleDeg = (a: Point, b: Point) => {
  const dx = b.x - a.x
  const dy = b.y - a.y
  return (Math.atan2(dy, dx) * 180) / Math.PI
}

const getMidpoint = (a: Point, b: Point): Point => ({
  x: (a.x + b.x) / 2,
  y: (a.y + b.y) / 2
})

const activeTouches = new Map<number, Point>()
const lastSinglePointer = ref<{ id: number; x: number; y: number } | null>(null)
const gestureStart = ref<{
  distance: number
  angleDeg: number
  midpoint: Point
  startScale: number
  startRotationDeg: number
  startTranslateX: number
  startTranslateY: number
} | null>(null)

const handleTouchStart = (e: TouchEvent) => {
  if (!props.modelValue) return
  enableTransition.value = false

  for (let i = 0; i < e.touches.length; i++) {
    const touch = e.touches[i]
    activeTouches.set(touch.identifier, { x: touch.clientX, y: touch.clientY })
  }

  if (activeTouches.size === 1) {
    const touch = e.touches[0]
    lastSinglePointer.value = { id: touch.identifier, x: touch.clientX, y: touch.clientY }
    gestureStart.value = null
  } else if (activeTouches.size === 2) {
    const pts = Array.from(activeTouches.values())
    const a = pts[0]
    const b = pts[1]
    gestureStart.value = {
      distance: getDistance(a, b),
      angleDeg: getAngleDeg(a, b),
      midpoint: getMidpoint(a, b),
      startScale: scale.value,
      startRotationDeg: rotationDeg.value,
      startTranslateX: translateX.value,
      startTranslateY: translateY.value
    }
    lastSinglePointer.value = null
  }
}

const handleTouchMove = (e: TouchEvent) => {
  if (!props.modelValue) return

  for (let i = 0; i < e.touches.length; i++) {
    const touch = e.touches[i]
    activeTouches.set(touch.identifier, { x: touch.clientX, y: touch.clientY })
  }

  if (activeTouches.size === 1 && lastSinglePointer.value) {
    const touch = e.touches[0]
    const dx = touch.clientX - lastSinglePointer.value.x
    const dy = touch.clientY - lastSinglePointer.value.y
    translateX.value += dx
    translateY.value += dy
    lastSinglePointer.value = { id: touch.identifier, x: touch.clientX, y: touch.clientY }
  } else if (activeTouches.size >= 2 && gestureStart.value) {
    const pts = Array.from(activeTouches.values())
    const a = pts[0]
    const b = pts[1]

    const distance = getDistance(a, b)
    const angleDeg = getAngleDeg(a, b)
    const midpoint = getMidpoint(a, b)

    const scaleFactor = gestureStart.value.distance > 0 ? distance / gestureStart.value.distance : 1
    const newScale = clamp(gestureStart.value.startScale * scaleFactor, MIN_SCALE, MAX_SCALE)

    const deltaAngle = angleDeg - gestureStart.value.angleDeg
    
    let newRotation = rotationDeg.value
    if (Math.abs(deltaAngle) > ROTATION_THRESHOLD) {
      newRotation = gestureStart.value.startRotationDeg + deltaAngle
    }

    // 小程序中通过系统信息获取屏幕尺寸替代 getBoundingClientRect
    const sysInfo = uni.getSystemInfoSync()
    const centerX = sysInfo.windowWidth / 2
    const centerY = sysInfo.windowHeight / 2
    
    const scaleRatio = newScale / gestureStart.value.startScale
    const startRelativeX = gestureStart.value.midpoint.x - centerX - gestureStart.value.startTranslateX
    const startRelativeY = gestureStart.value.midpoint.y - centerY - gestureStart.value.startTranslateY
    
    translateX.value = midpoint.x - centerX - startRelativeX * scaleRatio
    translateY.value = midpoint.y - centerY - startRelativeY * scaleRatio
    
    scale.value = newScale
    rotationDeg.value = newRotation
  }
}

const handleTouchEnd = (e: TouchEvent) => {
  for (let i = 0; i < e.changedTouches.length; i++) {
    activeTouches.delete(e.changedTouches[i].identifier)
  }

  if (activeTouches.size === 1) {
    const remainingId = Array.from(activeTouches.keys())[0]
    const pt = activeTouches.get(remainingId)
    if (pt) {
      lastSinglePointer.value = { id: remainingId, x: pt.x, y: pt.y }
    }
    gestureStart.value = null
  } else if (activeTouches.size < 1) {
    const startRotationDeg = gestureStart.value?.startRotationDeg || 0
    lastSinglePointer.value = null
    gestureStart.value = null

    const snappedRotation = snapToNearest90(rotationDeg.value, startRotationDeg)
    if (snappedRotation !== rotationDeg.value) {
      enableTransition.value = true
      rotationDeg.value = snappedRotation
      setTimeout(() => {
        enableTransition.value = false
      }, 300)
    }
  }
}

const handleSave = async () => {
  const url = currentImageUrl.value
  if (!url) return

  // 小程序中保存图片到相册
  uni.saveImageToPhotosAlbum({
    filePath: url, // 如果是网络地址可能需要先 uni.downloadFile
    success: () => {
      showMessage('已保存到相册', 'success')
    },
    fail: (err) => {
      console.error('保存失败', err)
      showMessage('保存失败', 'error')
    }
  })
}

// 移除不适用的事件监听
onMounted(() => {
})

onUnmounted(() => {
})
</script>

<style scoped lang="scss">
.image-viewer-root {
  // 确保图片预览层级高于其他自定义对话框（如 Modal，遮罩层 z-index=9000）
  position: fixed;
  inset: 0;
  z-index: var(--z-image-viewer-overlay);
}

.preview-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.95);
  display: flex;
  align-items: center;
  justify-content: center;
  backdrop-filter: blur(10px);
  cursor: pointer;
}

.close-btn {
  position: absolute;
  top: 20px;
  right: 20px;
  z-index: 10;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #ffffff;
  width: 36px;
  height: 36px;
  border-radius: 999px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s ease;
}

.close-btn:hover {
  background: rgba(0, 0, 0, 0.7);
  transform: scale(1.1);
}

.save-btn {
  position: absolute;
  top: 20px;
  right: 68px;
  z-index: 10;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #ffffff;
  height: 36px;
  padding: 0 12px;
  border-radius: 999px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s ease;
}

.save-btn:hover {
  background: rgba(0, 0, 0, 0.7);
  transform: scale(1.05);
}

.save-icon {
  width: 20px;
  height: 20px;
  display: block;
}

/* 导航按钮 */
.nav-btn {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  z-index: 10;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #ffffff;
  width: 48px;
  height: 48px;
  border-radius: 999px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s ease;
  font-size: 24px;
  font-weight: bold;
  padding: 0;
  line-height: 1;
}

.nav-btn:hover {
  background: rgba(0, 0, 0, 0.7);
  transform: translateY(-50%) scale(1.1);
}

.prev-btn {
  left: 20px;
}

.next-btn {
  right: 20px;
}

/* 图片计数器 */
.image-counter {
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 10;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  color: #ffffff;
  padding: 8px 16px;
  border-radius: 999px;
  font-size: 14px;
  font-weight: 500;
}

.preview-content {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 60px 20px 20px;
  touch-action: none;
}

.preview-image {
  max-width: 90vw;
  max-height: 90vh;
  width: auto;
  height: auto;
  object-fit: contain;
  border-radius: 8px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
  user-select: none;
  pointer-events: none;
  transform-origin: center center;
  will-change: transform;
}
</style>
